## **Pandas_Practice_Workbook**

## **Netflix Edition**

### **Section A — First Analysis of Data**

#### Q1. Load the dataset into a DataFrame called **df** and display the first 5 rows.

In [44]:
# Coding
import pandas as pd
df = pd.read_csv(r"C:\Users\HP\OneDrive\Desktop\Dataset\netflix_titles.csv")
df

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [45]:
# Coding
df.head(5)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

### Q2. Display the **last 7 rows** of the DataFrame.

In [46]:
# Coding 
df.tail(7)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
8800,s8801,TV Show,Zindagi Gulzar Hai,NaN,"Sanam Saeed, Fawad Khan, Ayesha Omer, Mehreen ...",Pakistan,"December 15, 2016",2012,TV-PG,1 Season,"International TV Shows, Romantic TV Shows, TV ...","Strong-willed, middle-class Kashaf and carefre..."
8801,s8802,Movie,Zinzana,Majid Al Ansari,"Ali Suliman, Saleh Bakri, Yasa, Ali Al-Jabri, ...","United Arab Emirates, Jordan","March 9, 2016",2015,TV-MA,96 min,"Dramas, International Movies, Thrillers",Recovering alcoholic Talal wakes up inside a s...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

### Q3. How many rows and columns does the dataset have?

In [47]:
# Coding 
print(df.shape)

(8807, 12)

### Q4. Display the names of all columns.

In [48]:
# Coding 
df.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='object')

### Q5. Use **info()** — which columns have missing values, and what is the data type of each column?

In [49]:
# Coding 
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: int64(1), object(11)
memory usage: 825.8+ KB

### Q6. Use **describe()** on the numeric columns. What is the minimum and maximum **release_year**?

In [50]:
# Coding 
df.describe()

       release_year
count   8807.000000
mean    2014.180198
std        8.819312
min     1925.000000
25%     2013.000000
50%     2017.000000
75%     2019.000000
max     2021.000000

##### The Maximum release_year is 2021 and Minimum release_year is 1925.

### Q7. Use **describe(include="object")** on the text columns. Which value appears most often in the **type** column?

In [51]:
# Coding 
df.describe(include= "object")

,show_id,type,title,director,cast,country,date_added,rating,duration,listed_in,description
count,8807,8807,8807,6173,7982,7976,8797,8803,8804,8807,8807
unique,8807,2,8807,4528,7692,748,1767,17,220,514,8775
top,s1,Movie,Dick Johnson Is Dead,Rajiv Chilaka,David Attenborough,United States,"January 1, 2020",TV-MA,1 Season,"Dramas, International Movies","Paranormal activity at a lush, abandoned prope..."
freq,1,6131,1,19,19,2818,109,3207,1793,362,4

### Q8. Count the missing values in **every** column with one command.

In [52]:
# Coding
df.isnull().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

### Q9. Which single column has the **most** missing values?

In [53]:
# Coding 
df.isnull().sum().idxmax()

'director'

### Q10. How many **unique** values are in the **rating** column? Display them.

In [54]:
# Coding 
df["rating"].unique()

array(['PG-13', 'TV-MA', 'PG', 'TV-14', 'TV-PG', 'TV-Y', 'TV-Y7', 'R',
       'TV-G', 'G', 'NC-17', '74 min', '84 min', '66 min', 'NR', nan,
       'TV-Y7-FV', 'UR'], dtype=object)

### Q11. Show 5 **random** rows using **sample()**.

In [55]:
# Coding 
df.sample(5)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
8339,s8340,Movie,The Healer,Paco Arango,"Oliver Jackson-Cohen, Camilla Luddington, Jona...","Spain, Canada, United States","June 1, 2020",2017,TV-14,108 min,"Children & Family Movies, Dramas, Faith & Spir...",A handyman who has hit rock bottom agrees to l...
1253,s1254,Movie,LEGO Marvel Spider-Man: Vexed by Venom,"Andrew Duncan, Ken Cunningham","Robbie Daymond, Ben Pronsky, Josh Keaton, Tara...",United States,"March 1, 2021",2019,TV-Y,22 min,"Children & Family Movies, Comedies",When Green Goblin and Venom team up for a disa...
7656,s7657,Movie,Once In A Lifetime Sessions with Noel Gallagher,Charlie Lightening,Noel Gallagher,United States,"August 1, 2018",2018,TV-MA,66 min,"Documentaries, Music & Musicals","Between scenes from an intimate performance, t..."
3037,s3038,TV Show,Medical Police,NaN,"Erinn Hayes, Rob Huebel, Malin Akerman, Rob Co...",United States,"January 10, 2020",2020,TV-MA,1 Season,"Crime TV Shows, TV Action & Adventure, TV Come...",Doctors Owen Maestro and Lola Spratt leave Chi...
8187,s8188,Movie,The American President,Rob Reiner,"Michael Douglas, Annette Bening, Martin Sheen,...",United States,"January 1, 2021",1995,PG-13,113 min,"Comedies, Dramas, Romantic Movies",The widowed president strikes up a romance wit...

### Q12. What is the memory usage of the DataFrame? (hint: **info()** or **memory_usage()**)

In [56]:
# Coding 
df.info()
#Note* info() display the total memory used by entire dataset.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: int64(1), object(11)
memory usage: 825.8+ KB

In [57]:
# Coding 
df.memory_usage() 
# Note* memory_usage() syntax display the memory usage by each column.

Index             128
show_id         70456
type            70456
title           70456
director        70456
cast            70456
country         70456
date_added      70456
release_year    70456
rating          70456
duration        70456
listed_in       70456
description     70456
dtype: int64

### Q13. Display the data type of only the **release_year** column.

In [58]:
# Coding 
df["release_year"].dtype

dtype('int64')

### Q14. Count how many titles are of each **type** using **value_counts()**.

In [59]:
# Coding 
df["type"].value_counts()

Movie      6131
TV Show    2676
Name: type, dtype: int64

### Q15. Check: does the dataset contain any **fully duplicated** rows?

In [60]:
# Coding
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
8802    False
8803    False
8804    False
8805    False
8806    False
Length: 8807, dtype: bool

## **Section B — Selection with** **[]**, **.loc**, **.iloc** 
* Default 0,1,2,... index. After ***set_index("show_id")***

### Q16. Select the **title** column as a **Series**.

In [61]:
# Coding 
df['title']

0        Dick Johnson Is Dead
1               Blood & Water
2                   Ganglands
3       Jailbirds New Orleans
4                Kota Factory
                ...
8802                   Zodiac
8803              Zombie Dumb
8804               Zombieland
8805                     Zoom
8806                   Zubaan
Name: title, Length: 8807, dtype: object

### Q17. Select the **title** column as a **DataFrame** (hint: double brackets).

In [62]:
# Coding 
df[['title']]

                      title
0      Dick Johnson Is Dead
1             Blood & Water
2                 Ganglands
3     Jailbirds New Orleans
4              Kota Factory
...                     ...
8802                 Zodiac
8803            Zombie Dumb
8804             Zombieland
8805                   Zoom
8806                 Zubaan

[8807 rows x 1 columns]

### Q18. Select the columns **title**, **type**, and **country** together.

In [63]:
# Coding 
df[["title", "type", "country"]]

                      title     type        country
0      Dick Johnson Is Dead    Movie  United States
1             Blood & Water  TV Show   South Africa
2                 Ganglands  TV Show            NaN
3     Jailbirds New Orleans  TV Show            NaN
4              Kota Factory  TV Show          India
...                     ...      ...            ...
8802                 Zodiac    Movie  United States
8803            Zombie Dumb  TV Show            NaN
8804             Zombieland    Movie  United States
8805                   Zoom    Movie  United States
8806                 Zubaan    Movie          India

[8807 rows x 3 columns]

### Q19. Select the first 10 rows using **.iloc**.

In [64]:
# Coding 
df.iloc[0:10]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
5,s6,TV Show,Midnight Mass,Mike Flanagan,"Kate Siegel, Zach Gilford, Hamish Linklater, H...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries",The arrival of a charismatic young priest brin...
6,s7,Movie,My Little Pony: A New Generation,"Robert Cullen, José Luis Ucha","Vanessa Hudgens, Kimiko Glenn, James Marsden, ...",NaN,"September 24, 2021",2021,PG,91 min,Children & Family Movies,Equestria's divided. But a bright-eyed hero be...
7,s8,Movie,Sankofa,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...","United States, Ghana, Burkina Faso, United Kin...","September 24, 2021",1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies","On a photo shoot in Ghana, an American model s..."
8,s9,TV Show,The Great British Baking Show,Andy Devonshire,"Mel Giedroyc, Sue Perkins, Mary Berry, Paul Ho...",United Kingdom,"September 24, 2021",2021,TV-14,9 Seasons,"British TV Shows, Reality TV",A talented batch of amateur bakers face off in...
9,s10,Movie,The Starling,Theodore Melfi,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",United States,"September 24, 2021",2021,PG-13,104 min,"Comedies, Dramas",A woman adjusting to life after a loss contend...

### Q20. Select rows with labels 10 to 20 using **.loc**. How many rows do you get and why?

In [65]:
# Coding 
df.loc[10:20]

# Note* we get 11 rows because, .loc use label index to extract the rows data from 10 to 20.

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
10,s11,TV Show,"Vendetta: Truth, Lies and The Mafia",NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, Docuseries, International TV S...","Sicily boasts a bold ""Anti-Mafia"" coalition. B..."
11,s12,TV Show,Bangkok Breaking,Kongkiat Komesiri,"Sukollawat Kanarot, Sushar Manaying, Pavarit M...",NaN,"September 23, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...","Struggling to earn a living in Bangkok, a man ..."
12,s13,Movie,Je Suis Karl,Christian Schwochow,"Luna Wedler, Jannis Niewöhner, Milan Peschel, ...","Germany, Czech Republic","September 23, 2021",2021,TV-MA,127 min,"Dramas, International Movies",After most of her family is murdered in a terr...
13,s14,Movie,Confessions of an Invisible Girl,Bruno Garotti,"Klara Castanho, Lucca Picon, Júlia Gomes, Marc...",NaN,"September 22, 2021",2021,TV-PG,91 min,"Children & Family Movies, Comedies",When the clever but socially-awkward Tetê join...
14,s15,TV Show,Crime Stories: India Detectives,NaN,NaN,NaN,"September 22, 2021",2021,TV-MA,1 Season,"British TV Shows, Crime TV Shows, Docuseries",Cameras following Bengaluru police on the job ...
15,s16,TV Show,Dear White People,NaN,"Logan Browning, Brandon P. Bell, DeRon Horton,...",United States,"September 22, 2021",2021,TV-MA,4 Seasons,"TV Comedies, TV Dramas",Students of color navigate the daily slights a...
16,s17,Movie,Europe's Most Dangerous Man: Otto Skorzeny in ...,"Pedro de Echave García, Pablo Azorín Williams",NaN,NaN,"September 22, 2021",2020,TV-MA,67 min,"Documentaries, International Movies",Declassified documents reveal the post-WWII li...
17,s18,TV Show,Falsa identidad,NaN,"Luis Ernesto Franco, Camila Sodi, Sergio Goyri...",Mexico,"September 22, 2021",2020,TV-MA,2 Seasons,"Crime TV Shows, Spanish-Language TV Shows, TV ...",Strangers Diego and Isabel flee their home in ...
18,s19,Movie,Intrusion,Adam Salky,"Freida Pinto, Logan Marshall-Green, Robert Joh...",NaN,"September 22, 2021",2021,TV-14,94 min,Thrillers,After a deadly home invasion at a couple’s new...
19,s20,TV Show,Jaguar,NaN,"Blanca Suárez, Iván Marcos, Óscar Casas, Adriá...",NaN,"September 22, 2021",2021,TV-MA,1 Season,"International TV Shows, Spanish-Language TV Sh...","In the 1960s, a Holocaust survivor joins a gro..."
20,s21,TV Show,Monsters Inside: The 24 Faces of Billy Milligan,Olivier Megaton,NaN,NaN,"September 22, 2021",2021,TV-14,1 Season,"Crime TV Shows, Docuseries, International TV S...","In the late 1970s, an accused serial rapist cl..."

### Q21. Using **.iloc**, select rows at positions 5 to 14 (10 rows). Compare with Q20 — why is the row count logic different?

In [66]:
# Coding 
df.iloc[4:14]

# Note* It is different compare to Q20 because, this question is index position based which is .iloc that looks the value according to index which start from 0
# where as Q20 is label based .loc which looks the value according to label.

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
5,s6,TV Show,Midnight Mass,Mike Flanagan,"Kate Siegel, Zach Gilford, Hamish Linklater, H...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries",The arrival of a charismatic young priest brin...
6,s7,Movie,My Little Pony: A New Generation,"Robert Cullen, José Luis Ucha","Vanessa Hudgens, Kimiko Glenn, James Marsden, ...",NaN,"September 24, 2021",2021,PG,91 min,Children & Family Movies,Equestria's divided. But a bright-eyed hero be...
7,s8,Movie,Sankofa,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...","United States, Ghana, Burkina Faso, United Kin...","September 24, 2021",1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies","On a photo shoot in Ghana, an American model s..."
8,s9,TV Show,The Great British Baking Show,Andy Devonshire,"Mel Giedroyc, Sue Perkins, Mary Berry, Paul Ho...",United Kingdom,"September 24, 2021",2021,TV-14,9 Seasons,"British TV Shows, Reality TV",A talented batch of amateur bakers face off in...
9,s10,Movie,The Starling,Theodore Melfi,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",United States,"September 24, 2021",2021,PG-13,104 min,"Comedies, Dramas",A woman adjusting to life after a loss contend...
10,s11,TV Show,"Vendetta: Truth, Lies and The Mafia",NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, Docuseries, International TV S...","Sicily boasts a bold ""Anti-Mafia"" coalition. B..."
11,s12,TV Show,Bangkok Breaking,Kongkiat Komesiri,"Sukollawat Kanarot, Sushar Manaying, Pavarit M...",NaN,"September 23, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...","Struggling to earn a living in Bangkok, a man ..."
12,s13,Movie,Je Suis Karl,Christian Schwochow,"Luna Wedler, Jannis Niewöhner, Milan Peschel, ...","Germany, Czech Republic","September 23, 2021",2021,TV-MA,127 min,"Dramas, International Movies",After most of her family is murdered in a terr...
13,s14,Movie,Confessions of an Invisible Girl,Bruno Garotti,"Klara Castanho, Lucca Picon, Júlia Gomes, Marc...",NaN,"September 22, 2021",2021,TV-PG,91 min,"Children & Family Movies, Comedies",When the clever but socially-awkward Tetê join...

### Q22. Using **.loc**, select rows 0 to 9 with only the columns **title** and **release_year**.

In [67]:
# Coding 
df.loc[0:9, ["title", "release_year"]]

                              title  release_year
0              Dick Johnson Is Dead          2020
1                     Blood & Water          2021
2                         Ganglands          2021
3             Jailbirds New Orleans          2021
4                      Kota Factory          2021
5                     Midnight Mass          2021
6  My Little Pony: A New Generation          2021
7                           Sankofa          1993
8     The Great British Baking Show          2021
9                      The Starling          2021

### Q23. Using **.iloc**, select the first 8 rows and the first 5 columns.

In [68]:
# Coding 
df.iloc[0:8, 0:5]

,show_id,type,title,director,cast
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi..."
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K..."
5,s6,TV Show,Midnight Mass,Mike Flanagan,"Kate Siegel, Zach Gilford, Hamish Linklater, H..."
6,s7,Movie,My Little Pony: A New Generation,"Robert Cullen, José Luis Ucha","Vanessa Hudgens, Kimiko Glenn, James Marsden, ..."
7,s8,Movie,Sankofa,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D..."

### Q24. Using **.iloc**, select the **last row** of the DataFrame.

In [69]:
# Coding 
df.iloc[8806, :]

show_id                                                     s8807
type                                                        Movie
title                                                      Zubaan
director                                              Mozez Singh
cast            Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...
country                                                     India
date_added                                          March 2, 2019
release_year                                                 2015
rating                                                      TV-14
duration                                                  111 min
listed_in          Dramas, International Movies, Music & Musicals
description     A scrappy but poor boy worms his way into a ty...
Name: 8806, dtype: object

In [70]:
# Coding 2
df.iloc[-1, :]

show_id                                                     s8807
type                                                        Movie
title                                                      Zubaan
director                                              Mozez Singh
cast            Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...
country                                                     India
date_added                                          March 2, 2019
release_year                                                 2015
rating                                                      TV-14
duration                                                  111 min
listed_in          Dramas, International Movies, Music & Musicals
description     A scrappy but poor boy worms his way into a ty...
Name: 8806, dtype: object

### Q25. Using **.iloc**, select the last 5 rows and the last 2 columns (negative positions).

In [71]:
# Coding 
df.iloc[-5:, -2: ]

,listed_in,description
8802,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

### Q26. Using **.loc**, get the value of **title** for the row with label 50.

In [72]:
# Coding 
df.loc[50, "title"]

'Dharmakshetra'

### Q27. Using **.iloc**, get the value in row position 100, column position 2. Which column is that?

In [73]:
# Coding 
df.iloc[100, 1]

# Note* the column name is "type".

'TV Show'

### Q28. Using **.iloc**, select every 100th row (hint: slicing with a step **::100**).

In [74]:
# Coding 
df.iloc[::100, :]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
100,s101,TV Show,Tobot Galaxy Detectives,NaN,"Austin Abell, Travis Turner, Cole Howard, Anna...",NaN,"September 7, 2021",2019,TV-Y7,2 Seasons,Kids' TV,An intergalactic device transforms toy cars in...
200,s201,Movie,Krishna Cottage,Santram Varma,"Sohail Khan, Isha Koppikar, Natassha, Rati Agn...",India,"August 27, 2021",2004,TV-14,124 min,"Action & Adventure, Horror Movies, Internation...",True love is put to the test when another woma...
300,s301,Movie,Vivo,"Kirk DeMicco, Brandon Jeffords","Lin-Manuel Miranda, Ynairaly Simo, Zoe Saldana...","Canada, United States","August 6, 2021",2021,PG,100 min,"Children & Family Movies, Music & Musicals",A music-loving kinkajou embarks on the journey...
400,s401,TV Show,Revelations: The Masters of the Universe: Reve...,NaN,"Kevin Smith, Tiffany Smith, Robert David, Sara...",NaN,"July 23, 2021",2021,TV-PG,1 Season,"Anime Series, Stand-Up Comedy & Talk Shows",Take a behind-the-scenes look at “Masters of t...
...,...,...,...,...,...,...,...,...,...,...,...,...
8400,s8401,Movie,The Long Goodbye: The Kara Tippetts Story,Jay Lyons,NaN,United States,"June 23, 2019",2019,TV-PG,87 min,"Documentaries, Faith & Spirituality","Faced with terminal breast cancer, a courageou..."
8500,s8501,Movie,The Search for Life in Space,Stephen Amezdroz,NaN,United States,"April 1, 2018",2016,TV-G,32 min,Documentaries,To determine whether we're alone in the univer...
8600,s8601,TV Show,Tobot,NaN,"Octavian Kaul, Valin Shinyei, Chelsea Miller, ...",Canada,"September 11, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows",They’re robots that can transform into cars – ...
8700,s8701,TV Show,Wartime Portraits,NaN,NaN,Poland,"September 15, 2016",2014,TV-MA,1 Season,"Docuseries, International TV Shows","Part live-action and part animation, this visu..."
8800,s8801,TV Show,Zindagi Gulzar Hai,NaN,"Sanam Saeed, Fawad Khan, Ayesha Omer, Mehreen ...",Pakistan,"December 15, 2016",2012,TV-PG,1 Season,"International TV Shows, Romantic TV Shows, TV ...","Strong-willed, middle-class Kashaf and carefre..."

### Q29. Using **.loc**, select rows 0 to 4 and **all** columns from **title** to **country** (label slicing on columns!).

In [75]:
# Coding 
df.loc[0:4, ["title", "director", "cast", "country"]]

,title,director,cast,country
0,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States
1,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa
2,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN
3,Jailbirds New Orleans,NaN,NaN,NaN
4,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India

### Q30. Select three specific rows by label — 3, 33, and 333 — in one **.loc** call.

In [76]:
# Coding 
df.loc[[3, 33, 333], :]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
33,s34,TV Show,Squid Game,NaN,"Lee Jung-jae, Park Hae-soo, Wi Ha-jun, Oh Youn...",NaN,"September 17, 2021",2021,TV-MA,1 Season,"International TV Shows, TV Dramas, TV Thrillers",Hundreds of cash-strapped players accept a str...
333,s334,Movie,Ferris Bueller's Day Off,John Hughes,"Matthew Broderick, Alan Ruck, Mia Sara, Jeffre...",United States,"August 1, 2021",1986,PG-13,103 min,"Classic Movies, Comedies, Cult Movies","After faking an illness to skip school, popula..."

### Q31. Set **show_id** as the index of **df** (keep it for the rest of Section B). Display the head.

In [77]:
# Coding 
df.set_index("show_id", inplace = True)
df.head(5)

,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
show_id,,,,,,,,,,,
s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

### Q32. Using **.loc**, select the row with label **"s1"**.

In [78]:
# Coding 
df.loc["s1", :]

type                                                        Movie
title                                        Dick Johnson Is Dead
director                                          Kirsten Johnson
cast                                                          NaN
country                                             United States
date_added                                     September 25, 2021
release_year                                                 2020
rating                                                      PG-13
duration                                                   90 min
listed_in                                           Documentaries
description     As her father nears the end of his life, filmm...
Name: s1, dtype: object

### Q33. Using **.loc**, select rows **"s10"** to **"s15"**. Does label slicing still include the end?

In [79]:
# Coding 
df.loc["s10":"s15", :]

,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
show_id,,,,,,,,,,,
s10,Movie,The Starling,Theodore Melfi,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",United States,"September 24, 2021",2021,PG-13,104 min,"Comedies, Dramas",A woman adjusting to life after a loss contend...
s11,TV Show,"Vendetta: Truth, Lies and The Mafia",NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, Docuseries, International TV S...","Sicily boasts a bold ""Anti-Mafia"" coalition. B..."
s12,TV Show,Bangkok Breaking,Kongkiat Komesiri,"Sukollawat Kanarot, Sushar Manaying, Pavarit M...",NaN,"September 23, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...","Struggling to earn a living in Bangkok, a man ..."
s13,Movie,Je Suis Karl,Christian Schwochow,"Luna Wedler, Jannis Niewöhner, Milan Peschel, ...","Germany, Czech Republic","September 23, 2021",2021,TV-MA,127 min,"Dramas, International Movies",After most of her family is murdered in a terr...
s14,Movie,Confessions of an Invisible Girl,Bruno Garotti,"Klara Castanho, Lucca Picon, Júlia Gomes, Marc...",NaN,"September 22, 2021",2021,TV-PG,91 min,"Children & Family Movies, Comedies",When the clever but socially-awkward Tetê join...
s15,TV Show,Crime Stories: India Detectives,NaN,NaN,NaN,"September 22, 2021",2021,TV-MA,1 Season,"British TV Shows, Crime TV Shows, Docuseries",Cameras following Bengaluru police on the job ...

### Q34. Using **.iloc**, select the row at position 0. Is it the same row as label **"s1"**?

In [80]:
# Coding 
df.iloc[0]

# Note* Yes, it is ture the index position 0 is label "s1"

type                                                        Movie
title                                        Dick Johnson Is Dead
director                                          Kirsten Johnson
cast                                                          NaN
country                                             United States
date_added                                     September 25, 2021
release_year                                                 2020
rating                                                      PG-13
duration                                                   90 min
listed_in                                           Documentaries
description     As her father nears the end of his life, filmm...
Name: s1, dtype: object

### Q35. Using **.loc**, get the **title** and **type** of the show with id **"s500"**.

In [81]:
# Coding 
df.loc["s500", ["title", "type"]]

title       Dogs
type     TV Show
Name: s500, dtype: object

### Q36. Using **.iloc**, select the row at position 499. Is its label **"s500"**? Explain why or why not in a comment.

In [82]:
# Coding
df.iloc[499]

# note* Yes, it is label 's500' because the same label 's500' become 499 in index position by it start from 0, 1, 2 so on where as, label start from mostly 1, 2, 3 and so on.

type                                                      TV Show
title                                                        Dogs
director                                                      NaN
cast                                                          NaN
country                                             United States
date_added                                           July 7, 2021
release_year                                                 2021
rating                                                      TV-PG
duration                                                2 Seasons
listed_in                                              Docuseries
description     These six intimate stories explore the abiding...
Name: s500, dtype: object

### Q37. Using **.loc**, select shows **"s1"**, **"s100"**, and **"s1000"** with columns **title** and **release_year**.

In [83]:
# Coding 
df.loc[["s1", "s100", 's1000'], ["title", "release_year"]]

                        title  release_year
show_id
s1       Dick Johnson Is Dead          2020
s100             On the Verge          2021
s1000                Stowaway          2021

### Q38. What happens if you run **df.loc[0]** now? Try it, read the error, and explain in a comment.

In [84]:
# Coding
df.loc[0]

# Note* the output provide error, because the label [0] doesnot exit in the dataset so, the the data cannot be extracted. In other case, if .iloc was in place of .loc the program would be error.

KeyError: 0

### Q39. Using **.iloc**, select rows at positions [0, 99, 999] in one call.

In [ ]:
# Coding 
df.iloc[[0, 99, 999], :]

### Q40. Reset the index back to 0,1,2,... using **reset_index()**. Display the head.

In [ ]:
# Coding 
df.reset_index(inplace = True)
df.head(5)

## **Section C — Conditions with .loc**
*Write every filter with ***df.loc[condition]*** or ***df.loc[condition, columns]*** style where possible.*

### Q41. Select all rows where **type** is **"Movie"**.

In [85]:
# Coding 
df.loc[df["type"]== "Movie"]

,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
show_id,,,,,,,,,,,
s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
s7,Movie,My Little Pony: A New Generation,"Robert Cullen, José Luis Ucha","Vanessa Hudgens, Kimiko Glenn, James Marsden, ...",NaN,"September 24, 2021",2021,PG,91 min,Children & Family Movies,Equestria's divided. But a bright-eyed hero be...
s8,Movie,Sankofa,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...","United States, Ghana, Burkina Faso, United Kin...","September 24, 2021",1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies","On a photo shoot in Ghana, an American model s..."
s10,Movie,The Starling,Theodore Melfi,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",United States,"September 24, 2021",2021,PG-13,104 min,"Comedies, Dramas",A woman adjusting to life after a loss contend...
s13,Movie,Je Suis Karl,Christian Schwochow,"Luna Wedler, Jannis Niewöhner, Milan Peschel, ...","Germany, Czech Republic","September 23, 2021",2021,TV-MA,127 min,"Dramas, International Movies",After most of her family is murdered in a terr...
...,...,...,...,...,...,...,...,...,...,...,...
s8802,Movie,Zinzana,Majid Al Ansari,"Ali Suliman, Saleh Bakri, Yasa, Ali Al-Jabri, ...","United Arab Emirates, Jordan","March 9, 2016",2015,TV-MA,96 min,"Dramas, International Movies, Thrillers",Recovering alcoholic Talal wakes up inside a s...
s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

### Q42. Select all rows where **type** is **"TV Show"** — show only **title** and **country** using one **.loc** call.

In [86]:
# Coding 
df.loc[df["type"]=="TV Show", ["type", "title", "country"]]

,type,title,country
show_id,,,
s2,TV Show,Blood & Water,South Africa
s3,TV Show,Ganglands,NaN
s4,TV Show,Jailbirds New Orleans,NaN
s5,TV Show,Kota Factory,India
s6,TV Show,Midnight Mass,NaN
...,...,...,...
s8796,TV Show,Yu-Gi-Oh! Arc-V,"Japan, Canada"
s8797,TV Show,Yunus Emre,Turkey
s8798,TV Show,Zak Storm,"United States, France, South Korea, Indonesia"
s8801,TV Show,Zindagi Gulzar Hai,Pakistan
s8804,TV Show,Zombie Dumb,NaN

### Q43. Select all titles released in 2021.

In [87]:
# Coding 
df.loc[df["release_year"]==2021, ["title", "release_year"]]

                             title  release_year
show_id
s2                   Blood & Water          2021
s3                       Ganglands          2021
s4           Jailbirds New Orleans          2021
s5                    Kota Factory          2021
s6                   Midnight Mass          2021
...                            ...           ...
s1469    What Happened to Mr. Cha?          2021
s1552                        Hilda          2021
s1697                 Polly Pocket          2021
s2921                Love Is Blind          2021
s8438       The Netflix Afterparty          2021

[592 rows x 2 columns]

### Q44. Select all titles released **before** 2000.

In [88]:
# Coding 
df.loc[df["release_year"] < 2000, ["title","release_year"]]

                                       title  release_year
show_id
s8                                   Sankofa          1993
s23                          Avvai Shanmughi          1996
s25                                    Jeans          1998
s27                           Minsara Kanavu          1997
s42                                     Jaws          1975
...                                      ...           ...
s8746    Willy Wonka & the Chocolate Factory          1971
s8749                   Winter of Our Dreams          1981
s8764        WWII: Report from the Aleutians          1943
s8765                             Wyatt Earp          1994
s8793                            Young Tiger          1973

[525 rows x 2 columns]

### Q45. Select all titles released between 2015 and 2020 (inclusive) — two conditions with **&**.

In [89]:
# Coding 
df.loc[(df["release_year"] > 2015) & (df["release_year"] < 2020), ["title", "release_year"]]

                             title  release_year
show_id
s22         Resurrection: Ertugrul          2018
s38                    Angry Birds          2018
s39            Birth of the Dragon          2017
s74                   King of Boys          2018
s88                  Titipo Titipo          2019
...                            ...           ...
s8788    You Can’t Fight Christmas          2017
s8795                       اشتباك          2016
s8797                   Yunus Emre          2016
s8798                    Zak Storm          2016
s8804                  Zombie Dumb          2018

[4111 rows x 2 columns]

### Q46. Select all Movies released after 2019 (two conditions).

In [90]:
# Coding 
df.loc[(df["type"]== "Movie") & (df["release_year"]> 2019), ["type", "release_year", "title"]]

          type  release_year                               title
show_id
s1       Movie          2020                Dick Johnson Is Dead
s7       Movie          2021    My Little Pony: A New Generation
s10      Movie          2021                        The Starling
s13      Movie          2021                        Je Suis Karl
s14      Movie          2021    Confessions of an Invisible Girl
...        ...           ...                                 ...
s3047    Movie          2020       All the Freckles in the World
s3061    Movie          2020                       Ghost Stories
s5973    Movie          2020                    #cats_the_mewvie
s7595    Movie          2020  Norm of the North: Family Vacation
s8100    Movie          2020                         Straight Up

[794 rows x 3 columns]

### Q47. Select all titles where **rating** is **"TV-MA"**.

In [91]:
# Coding 
df.loc[df['rating'] == "TV-MA", ["title", "rating"]]

                          title rating
show_id
s2                Blood & Water  TV-MA
s3                    Ganglands  TV-MA
s4        Jailbirds New Orleans  TV-MA
s5                 Kota Factory  TV-MA
s6                Midnight Mass  TV-MA
...                         ...    ...
s8763           Wrong Side Raju  TV-MA
s8770    Y.M.I.: Yeh Mera India  TV-MA
s8789              You Carry Me  TV-MA
s8799                  Zed Plus  TV-MA
s8802                   Zinzana  TV-MA

[3207 rows x 2 columns]

### Q48. Select all titles where **rating** is either **"PG"** or **"PG-13"** using **.isin()**.

In [92]:
# Coding 
df.loc[(df["rating"]== "PG") | (df["rating"] == "PG-13"), ["title", "rating"]]

                                    title rating
show_id
s1                   Dick Johnson Is Dead  PG-13
s7       My Little Pony: A New Generation     PG
s10                          The Starling  PG-13
s28                             Grown Ups  PG-13
s29                            Dark Skies  PG-13
...                                   ...    ...
s8768             XXX: State of the Union  PG-13
s8777                          Yellowbird     PG
s8783                         Yoga Hosers  PG-13
s8794                Yours, Mine and Ours     PG
s8806                                Zoom     PG

[777 rows x 2 columns]

### Q49. Select all titles where **rating** is **NOT** **"TV-MA"** (hint: **~** or **!=**).

In [93]:
# Coding 
df.loc[~(df["rating"] == "TV-MA"), ["title", "rating"]]

                                    title rating
show_id
s1                   Dick Johnson Is Dead  PG-13
s7       My Little Pony: A New Generation     PG
s9          The Great British Baking Show  TV-14
s10                          The Starling  PG-13
s14      Confessions of an Invisible Girl  TV-PG
...                                   ...    ...
s8803                              Zodiac      R
s8804                         Zombie Dumb  TV-Y7
s8805                          Zombieland      R
s8806                                Zoom     PG
s8807                              Zubaan  TV-14

[5600 rows x 2 columns]

### Q50. Select all titles where **country** is exactly **"India"**.

In [94]:
# Coding 
df.loc[df["country"] == "India", ["title", "country"]]

                                 title country
show_id
s5                        Kota Factory   India
s25                              Jeans   India
s40                       Chhota Bheem   India
s51                      Dharmakshetra   India
s67      Raja Rasoi Aur Anya Kahaniyan   India
...                                ...     ...
s8774              Yanda Kartavya Aahe   India
s8776                  Yeh Meri Family   India
s8799                         Zed Plus   India
s8800                            Zenda   India
s8807                           Zubaan   India

[972 rows x 2 columns]

### Q51. Select all titles where **country** **contains** **"India"** (hint: **str.contains**, use **na=False**). Why is the row count different from the previous question?

In [95]:
# Coding
df.loc[df["country"].str.contains("India", na = False)]

# Note* The row count may differ because str.contains() searches for "India" anywhere within the country text, whereas the previous question used an exact match.
# For Example: show_id 's30' did not count in previous question, because the previous question was about exact match called 'India'. However, in this question, 
# show_id 's30' appeared because, country name 'India' is also with United States and France.

,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
show_id,,,,,,,,,,,
s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
s25,Movie,Jeans,S. Shankar,"Prashanth, Aishwarya Rai Bachchan, Sri Lakshmi...",India,"September 21, 2021",1998,TV-14,166 min,"Comedies, International Movies, Romantic Movies",When the father of the man she loves insists t...
s30,Movie,Paranoia,Robert Luketic,"Liam Hemsworth, Gary Oldman, Amber Heard, Harr...","United States, India, France","September 19, 2021",2013,PG-13,106 min,Thrillers,"Blackmailed by his company's CEO, a low-level ..."
s40,TV Show,Chhota Bheem,NaN,"Vatsal Dubey, Julie Tejwani, Rupa Bhimani, Jig...",India,"September 16, 2021",2021,TV-Y7,3 Seasons,Kids' TV,"A brave, energetic little boy with superhuman ..."
s51,TV Show,Dharmakshetra,NaN,"Kashmira Irani, Chandan Anand, Dinesh Mehta, A...",India,"September 15, 2021",2014,TV-PG,1 Season,"International TV Shows, TV Dramas, TV Sci-Fi &...","After the ancient Great War, the god Chitragup..."
...,...,...,...,...,...,...,...,...,...,...,...
s8774,Movie,Yanda Kartavya Aahe,Kedar Shinde,"Ankush Choudhary, Smita Shewale, Mohan Joshi, ...",India,"January 1, 2018",2006,TV-PG,151 min,"Comedies, Dramas, International Movies",Thanks to an arranged marriage that was design...
s8776,TV Show,Yeh Meri Family,NaN,"Vishesh Bansal, Mona Singh, Akarsh Khurana, Ah...",India,"August 31, 2018",2018,TV-PG,1 Season,"International TV Shows, TV Comedies","In the summer of 1998, middle child Harshu bal..."
s8799,Movie,Zed Plus,Chandra Prakash Dwivedi,"Adil Hussain, Mona Singh, K.K. Raina, Sanjay M...",India,"December 31, 2019",2014,TV-MA,131 min,"Comedies, Dramas, International Movies",A philandering small-town mechanic's political...
s8800,Movie,Zenda,Avadhoot Gupte,"Santosh Juvekar, Siddharth Chandekar, Sachit P...",India,"February 15, 2018",2009,TV-14,120 min,"Dramas, International Movies",A change in the leadership of a political part...
s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

### Q52. Select all Movies from the United States — show only **title** and **release_year**.

In [96]:
# Coding
df.loc[(df["type"]=="Movie") & (df["country"] == "United States"), ["title", "release_year", "country", "type"]]

                        title  release_year        country   type
show_id
s1       Dick Johnson Is Dead          2020  United States  Movie
s10              The Starling          2021  United States  Movie
s28                 Grown Ups          2010  United States  Movie
s29                Dark Skies          2013  United States  Movie
s42                      Jaws          1975  United States  Movie
...                       ...           ...            ...    ...
s8792             Young Adult          2011  United States  Movie
s8794    Yours, Mine and Ours          2005  United States  Movie
s8803                  Zodiac          2007  United States  Movie
s8805              Zombieland          2009  United States  Movie
s8806                    Zoom          2006  United States  Movie

[2058 rows x 4 columns]

### Q53. Select all titles where **director** is missing (hint: **isna()**).

In [97]:
# Coding 
df.loc[df["director"].isna(), ["title", "director"]]

                                       title director
show_id
s2                             Blood & Water      NaN
s4                     Jailbirds New Orleans      NaN
s5                              Kota Factory      NaN
s11      Vendetta: Truth, Lies and The Mafia      NaN
s15          Crime Stories: India Detectives      NaN
...                                      ...      ...
s8796                        Yu-Gi-Oh! Arc-V      NaN
s8797                             Yunus Emre      NaN
s8798                              Zak Storm      NaN
s8801                     Zindagi Gulzar Hai      NaN
s8804                            Zombie Dumb      NaN

[2634 rows x 2 columns]

### Q54. Select all titles where **director** is **not** missing.

In [98]:
# Coding 
df.loc[~(df["director"]== "NaN"), ["title", "director"]]

                         title         director
show_id
s1        Dick Johnson Is Dead  Kirsten Johnson
s2               Blood & Water              NaN
s3                   Ganglands  Julien Leclercq
s4       Jailbirds New Orleans              NaN
s5                Kota Factory              NaN
...                        ...              ...
s8803                   Zodiac    David Fincher
s8804              Zombie Dumb              NaN
s8805               Zombieland  Ruben Fleischer
s8806                     Zoom     Peter Hewitt
s8807                   Zubaan      Mozez Singh

[8807 rows x 2 columns]

In [99]:
# Coding 
df.loc[df["director"].notna()]

,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
show_id,,,,,,,,,,,
s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
s6,TV Show,Midnight Mass,Mike Flanagan,"Kate Siegel, Zach Gilford, Hamish Linklater, H...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries",The arrival of a charismatic young priest brin...
s7,Movie,My Little Pony: A New Generation,"Robert Cullen, José Luis Ucha","Vanessa Hudgens, Kimiko Glenn, James Marsden, ...",NaN,"September 24, 2021",2021,PG,91 min,Children & Family Movies,Equestria's divided. But a bright-eyed hero be...
s8,Movie,Sankofa,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...","United States, Ghana, Burkina Faso, United Kin...","September 24, 2021",1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies","On a photo shoot in Ghana, an American model s..."
...,...,...,...,...,...,...,...,...,...,...,...
s8802,Movie,Zinzana,Majid Al Ansari,"Ali Suliman, Saleh Bakri, Yasa, Ali Al-Jabri, ...","United Arab Emirates, Jordan","March 9, 2016",2015,TV-MA,96 min,"Dramas, International Movies, Thrillers",Recovering alcoholic Talal wakes up inside a s...
s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

### Q55. Select all TV Shows released in 2020 **or** 2021.

In [100]:
# Coding 
df.loc[(df["type"]== "TV Show") & (df["release_year"]== 2020) | (df["release_year"]== 2021), :]

,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
show_id,,,,,,,,,,,
s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
s6,TV Show,Midnight Mass,Mike Flanagan,"Kate Siegel, Zach Gilford, Hamish Linklater, H...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries",The arrival of a charismatic young priest brin...
...,...,...,...,...,...,...,...,...,...,...,...
s3370,TV Show,BoJack Horseman,NaN,"Will Arnett, Aaron Paul, Amy Sedaris, Alison B...",United States,"October 25, 2019",2020,TV-MA,6 Seasons,TV Comedies,Meet the most beloved sitcom horse of the '90s...
s3434,TV Show,The Hook Up Plan,NaN,"Marc Ruchmann, Zita Hanrot, Sabrina Ouazani, J...",France,"October 11, 2019",2020,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...","When Parisian Elsa gets hung up on her ex, her..."
s8126,TV Show,Super Wings,NaN,"Luca Padovan, Evan Smolin, Junah Jang, Colin C...","United States, South Korea, China","December 1, 2020",2020,TV-Y,3 Seasons,"Kids' TV, Korean TV Shows",A cheerful jet and his transforming pals striv...
s8133,TV Show,Surviving R. Kelly Part II: The Reckoning,NaN,R. Kelly,United States,"April 13, 2020",2020,TV-MA,1 Season,"Crime TV Shows, Docuseries",As more women come forward with harrowing accu...
s8438,TV Show,The Netflix Afterparty,NaN,"David Spade, London Hughes, Fortune Feimster",United States,"January 2, 2021",2021,TV-MA,1 Season,"Stand-Up Comedy & Talk Shows, TV Comedies","Hosts David Spade, Fortune Feimster and London..."

### Q56. Select all titles whose **title** starts with the letter **"A"** (hint: **str.startswith**, **na=False**).

In [101]:
# Coding
df.loc[df["title"].str.startswith("A", na=False)]

,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
show_id,,,,,,,,,,,
s23,Movie,Avvai Shanmughi,K.S. Ravikumar,"Kamal Hassan, Meena, Gemini Ganesan, Heera Raj...",NaN,"September 21, 2021",1996,TV-PG,161 min,"Comedies, International Movies",Newly divorced and denied visitation rights wi...
s31,Movie,Ankahi Kahaniya,"Ashwiny Iyer Tiwari, Abhishek Chaubey, Saket C...","Abhishek Banerjee, Rinku Rajguru, Delzad Hiwal...",NaN,"September 17, 2021",2021,TV-14,111 min,"Dramas, Independent Movies, International Movies","As big city life buzzes around them, lonely so..."
s38,TV Show,Angry Birds,NaN,"Antti Pääkkönen, Heljä Heikkinen, Lynne Guagli...",Finland,"September 16, 2021",2018,TV-Y7,1 Season,"Kids' TV, TV Comedies","Birds Red, Chuck and their feathered friends h..."
s72,Movie,A StoryBots Space Adventure,David A. Vargas,"Evan Spiridellis, Erin Fitzgerald, Jeff Gill, ...",NaN,"September 14, 2021",2021,TV-Y,13 min,Children & Family Movies,Join the StoryBots and the space travelers of ...
s106,Movie,Angamaly Diaries,Lijo Jose Pellissery,"Antony Varghese, Reshma Rajan, Binny Rinky Ben...",India,"September 5, 2021",2017,TV-14,128 min,"Action & Adventure, Comedies, Dramas",After growing up amidst the gang wars of his h...
...,...,...,...,...,...,...,...,...,...,...,...
s6199,TV Show,Aussie Gold Hunters,NaN,NaN,Australia,"August 1, 2017",2016,TV-MA,1 Season,"Docuseries, International TV Shows, Reality TV",Three teams of gold hunters battle all manner ...
s6200,Movie,Automata,Gabe Ibáñez,"Antonio Banderas, Dylan McDermott, Melanie Gri...","Bulgaria, United States, Spain, Canada","September 8, 2017",2014,R,110 min,"International Movies, Sci-Fi & Fantasy, Thrillers","In a dystopian future, an insurance adjuster f..."
s6201,Movie,Avengers: Infinity War,"Anthony Russo, Joe Russo","Robert Downey Jr., Josh Brolin, Mark Ruffalo, ...",United States,"December 25, 2018",2018,PG-13,150 min,"Action & Adventure, Sci-Fi & Fantasy",Superheroes amass to stop intergalactic sociop...
s6202,Movie,Avicii: True Stories,Levan Tsikurishvili,Avicii,"Sweden, Netherlands","December 28, 2018",2017,TV-MA,97 min,"Documentaries, International Movies, Music & M...","Follow the meteoric rise of Tim Bergling, aka ..."
s6203,Movie,Azhar,Anthony D'Souza,"Emraan Hashmi, Prachi Desai, Nargis Fakhri, La...",India,"April 12, 2019",2016,TV-14,129 min,"Dramas, International Movies, Sports Movies",This biopic traces the tumultuous life and car...

### Q57. Select all titles whose **title** contains the word **"Love"**.

In [102]:
# Coding 
df.loc[df["title"].str.contains("Love", na=False)]

,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
show_id,,,,,,,,,,,
s26,TV Show,Love on the Spectrum,NaN,Brooke Satchwell,Australia,"September 21, 2021",2021,TV-14,2 Seasons,"Docuseries, International TV Shows, Reality TV",Finding love can be hard for anyone. For young...
s159,Movie,Love Don't Cost a Thing,Troy Byer,"Nick Cannon, Christina Milian, Kenan Thompson,...",United States,"September 1, 2021",2003,PG-13,101 min,"Comedies, Romantic Movies",A nerdy teen tries to make himself cool by ass...
s160,Movie,Love in a Puff,Pang Ho-cheung,"Miriam Chin Wah Yeung, Shawn Yue, Singh Hartih...",Hong Kong,"September 1, 2021",2010,TV-MA,103 min,"Comedies, Dramas, International Movies",When the Hong Kong government enacts a ban on ...
s207,Movie,"LSD: Love, Sex Aur Dhokha",Dibakar Banerjee,"Nushrat Bharucha, Anshuman Jha, Neha Chauhan, ...",India,"August 27, 2021",2010,TV-MA,112 min,"Dramas, Independent Movies, International Movies",This provocative drama examines how the voyeur...
s228,Movie,Really Love,Angel Kristi Williams,"Kofi Siriboe, Yootha Wong-Loi-Sing, Michael Ea...",United States,"August 25, 2021",2020,TV-MA,95 min,"Dramas, Independent Movies, Romantic Movies",A rising Black painter tries to break into a c...
...,...,...,...,...,...,...,...,...,...,...,...
s8568,TV Show,The Year of Happiness and Love,NaN,"Amber Kuo, James Wen, Weber Yang, Sonia Sui, N...",Taiwan,"September 1, 2016",2009,TV-PG,1 Season,"International TV Shows, Romantic TV Shows, TV ...",Jiang Chen-bo is a loser without prospects for...
s8576,TV Show,This Is My Love,NaN,"Jin-mo Joo, Sa-rang Kim, Junior, Ja-in Lee, Su...",South Korea,"May 22, 2017",2015,TV-14,1 Season,"International TV Shows, Korean TV Shows, Roman...",A renowned actor who is still pining over the ...
s8650,Movie,Two Lovers and a Bear,Kim Nguyen,"Dane DeHaan, Tatiana Maslany, Gordon Pinsent, ...",Canada,"May 2, 2017",2016,R,95 min,"Dramas, Independent Movies, Romantic Movies",A troubled couple living near the North Pole b...
s8722,TV Show,What Is Love?,NaN,"Chris Wu, Jade Chou, Duncan Lai, King Chin, Ki...",Taiwan,"January 1, 2017",2012,TV-14,1 Season,"International TV Shows, Romantic TV Shows, TV ...",A 32-year-old romantic looking for a long-term...
s8726,Movie,What's Up With Love?,"Rudy Soedjarwo, Riri Riza","Dian Sastrowardoyo, Nicholas Saputra, Ladya Ch...",Indonesia,"December 8, 2018",2002,R,110 min,"Dramas, International Movies, Romantic Movies",A popular high school girl strains her relatio...

### Q58. Using **.loc** with a condition, show the **title**, **rating**, and **release_year** of all Movies rated **"R"**.

In [103]:
# Coding 
df.loc[(df["type"]== "Movie") & (df["rating"]== "R"), ["title", "rating", "release_year", "type"]]

                               title rating  release_year   type
show_id
s47                       Safe House      R          2012  Movie
s49                     Training Day      R          2001  Movie
s82                             Kate      R          2021  Movie
s123                      In the Cut      R          2003  Movie
s132     Blade Runner: The Final Cut      R          1982  Movie
...                              ...    ...           ...    ...
s8766                             XX      R          2017  Movie
s8769              Y Tu Mamá También      R          2001  Movie
s8792                    Young Adult      R          2011  Movie
s8803                         Zodiac      R          2007  Movie
s8805                     Zombieland      R          2009  Movie

[797 rows x 4 columns]

### Q59. Count how many Movies were released after 2015 (condition + **len()** or **.shape**).

In [104]:
# Coding 
a = df.loc[(df["type"]== "Movie") & (df["release_year"]> 2015)]
len(a)

3619

### Q60. Challenge: select all Movies that are from India **or** Nepal and released after 2010 — careful with brackets around the **|** condition!

In [105]:
# Coding 
df.loc[(df["type"]== "Movie") & (df["release_year"]> 2010) & (df["country"]== "India") | (df["country"]== "Nepal")]

,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
show_id,,,,,,,,,,,
s106,Movie,Angamaly Diaries,Lijo Jose Pellissery,"Antony Varghese, Reshma Rajan, Binny Rinky Ben...",India,"September 5, 2021",2017,TV-14,128 min,"Action & Adventure, Comedies, Dramas",After growing up amidst the gang wars of his h...
s117,Movie,Dhanak,Nagesh Kukunoor,"Krrish Chhabria, Hetal Gada, Vipin Sharma, Gul...",India,"September 2, 2021",2015,TV-PG,114 min,"Comedies, Dramas, Independent Movies",A movie-loving 10-year-old and her blind littl...
s119,Movie,Gurgaon,Shanker Raman,"Akshay Oberoi, Pankaj Tripathi, Ragini Khanna,...",India,"September 2, 2021",2017,TV-14,106 min,"Dramas, International Movies, Thrillers",When the daughter of a wealthy family returns ...
s127,Movie,Shikara,Vidhu Vinod Chopra,"Aadil Khan, Sadia Khateeb, Zain Khan Durrani, ...",India,"September 2, 2021",2020,TV-14,115 min,"Dramas, International Movies, Romantic Movies",A couple must strive to remain resilient after...
s191,Movie,Thimmarusu,Sharan Koppisetty,"Satya Dev, Priyanka Jawalkar, Brahmaji",India,"August 28, 2021",2021,TV-14,125 min,"Dramas, International Movies",Eight years after a young man is framed for mu...
...,...,...,...,...,...,...,...,...,...,...,...
s8763,Movie,Wrong Side Raju,Mikhil Musale,"Pratik Gandhi, Kimberley Louisa McBeath, Asif ...",India,"October 1, 2017",2016,TV-MA,140 min,"Dramas, International Movies",The life of a chauffeur and part-time bootlegg...
s8772,Movie,Yaara O Dildaara,Ksshitij Chaudhary,"Harbhajan Mann, Tulip Joshi, Kabir Bedi, Gulza...",India,"November 1, 2017",2011,TV-14,132 min,"Dramas, International Movies, Music & Musicals",The patriarch of a wealthy family with one ind...
s8773,Movie,Yamla Pagla Deewana 2,Sangeeth Sivan,"Dharmendra, Sunny Deol, Bobby Deol, Neha Sharm...",India,"May 1, 2017",2013,TV-14,147 min,"Action & Adventure, Comedies, International Mo...","Up to his old tricks, con man Dharam poses as ..."
s8799,Movie,Zed Plus,Chandra Prakash Dwivedi,"Adil Hussain, Mona Singh, K.K. Raina, Sanjay M...",India,"December 31, 2019",2014,TV-MA,131 min,"Comedies, Dramas, International Movies",A philandering small-town mechanic's political...
s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

## **Section D — Sorting**

### Q61. Sort the DataFrame by **release_year** ascending. Show the head — what are the oldest titles?

In [106]:
# Coding 
df.sort_values(by= "release_year")

# Note* the oldest title is Pionners:First Women Flimmakers - 1925 and Prelude to War - 1942.

,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
show_id,,,,,,,,,,,
s4251,TV Show,Pioneers: First Women Filmmakers*,NaN,NaN,NaN,"December 30, 2018",1925,TV-14,1 Season,TV Shows,This collection restores films from women who ...
s7791,Movie,Prelude to War,Frank Capra,NaN,United States,"March 31, 2017",1942,TV-14,52 min,"Classic Movies, Documentaries",Frank Capra's documentary chronicles the rise ...
s8206,Movie,The Battle of Midway,John Ford,"Henry Fonda, Jane Darwell",United States,"March 31, 2017",1942,TV-14,18 min,"Classic Movies, Documentaries",Director John Ford captures combat footage of ...
s8661,Movie,Undercover: How to Operate Behind Enemy Lines,John Ford,NaN,United States,"March 31, 2017",1943,TV-PG,61 min,"Classic Movies, Documentaries",This World War II-era training film dramatizes...
s8740,Movie,Why We Fight: The Battle of Russia,"Frank Capra, Anatole Litvak",NaN,United States,"March 31, 2017",1943,TV-PG,82 min,Documentaries,This installment of Frank Capra's acclaimed do...
...,...,...,...,...,...,...,...,...,...,...,...
s863,TV Show,Special,NaN,"Ryan O'Connell, Jessica Hecht, Punam Patel, Ma...",United States,"May 20, 2021",2021,TV-MA,2 Seasons,TV Comedies,A young gay man with cerebral palsy branches o...
s862,Movie,Little Singham Future mein Satakli,Prakash Satam,"Anamaya Verma, Ganesh Divekar, Jigna Bharadhwa...",NaN,"May 20, 2021",2021,TV-Y7,47 min,"Children & Family Movies, Comedies",Little Singham and his crew travel to the year...
s858,TV Show,The Neighbor,NaN,"Quim Gutiérrez, Clara Lago, Adrián Pino, Catel...",Spain,"May 21, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Spanish-Language TV Sh...",Self-centered Javier's life gets a bit messy w...
s877,TV Show,Alma Matters,NaN,NaN,India,"May 14, 2021",2021,TV-MA,1 Season,"Docuseries, International TV Shows",Alumni of India’s elite academic institutes sh...
s966,TV Show,Yasuke,NaN,"LaKeith Stanfield, Takehiro Hira, Maya Tanida,...",NaN,"April 29, 2021",2021,TV-MA,1 Season,"Anime Series, International TV Shows",A peaceful boatman once known as the Black Sam...

### Q62. Sort by **release_year** **descending**. Show the 10 newest titles.

In [107]:
# Coding 
df.sort_values(by= "release_year", ascending= False).head(10)

,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
show_id,,,,,,,,,,,
s694,Movie,Ali & Ratu Ratu Queens,Lucky Kuswandi,"Iqbaal Ramadhan, Nirina Zubir, Asri Welas, Tik...",NaN,"June 17, 2021",2021,TV-14,101 min,"Comedies, Dramas, International Movies","After his father's passing, a teenager sets ou..."
s782,Movie,Black Holes | The Edge of All We Know,Peter Galison,NaN,NaN,"June 2, 2021",2021,TV-14,99 min,Documentaries,Follow scientists on their quest to understand...
s763,Movie,Sweet & Sour,Lee Kae-byeok,"Jang Ki-yong, Chae Soo-bin, Jung Soo-jung",South Korea,"June 4, 2021",2021,TV-14,103 min,"Comedies, International Movies, Romantic Movies",Faced with real-world opportunities and challe...
s764,TV Show,Sweet Tooth,NaN,"Nonso Anozie, Christian Convery, Adeel Akhtar,...",United States,"June 4, 2021",2021,TV-14,1 Season,"TV Action & Adventure, TV Dramas, TV Sci-Fi & ...",On a perilous adventure across a post-apocalyp...
s765,Movie,Trippin' with the Kandasamys,Jayan Moodley,"Jailoshini Naidoo, Maeshni Naicker, Madhushan ...",South Africa,"June 4, 2021",2021,TV-14,94 min,"Comedies, International Movies, Romantic Movies","To rekindle their marriages, best friends-turn..."
s766,Movie,Xtreme,Daniel Benmayor,"Teo García, Óscar Jaenada, Óscar Casas, Andrea...",Spain,"June 4, 2021",2021,TV-MA,112 min,"Action & Adventure, International Movies","In this fast-paced and action-packed thriller,..."
s767,Movie,Alan Saldaña: Locked Up,Alex Díaz,Alan Saldaña,Mexico,"June 3, 2021",2021,TV-MA,49 min,Stand-Up Comedy,"Mexican comedian Alan Saldaña is back, poking ..."
s768,TV Show,Creator's File: GOLD,NaN,"Ryuji Akiyama, Ryusei Yokohama, Yumi Adachi, A...",Japan,"June 3, 2021",2021,TV-14,1 Season,"International TV Shows, TV Comedies",Comedian Ryuji Akiyama satirizes top “creators...
s769,Movie,Dancing Queens,Helena Bergström,"Molly Nutley, Fredrik Quiñones, Marie Göranzon...",Sweden,"June 3, 2021",2021,TV-MA,111 min,"Comedies, Dramas, International Movies",A dancer who gets a job cleaning at a struggli...
s771,Movie,Myriam Fares: The Journey,Myriam Fares,Myriam Fares,United Arab Emirates,"June 3, 2021",2021,TV-14,72 min,"Documentaries, International Movies, Music & M...","From pregnancy to album preparations, Lebanese..."

### Q63. Sort by **title** alphabetically.

In [108]:
# Coding 
df.sort_values(by="title").head(10)

,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
show_id,,,,,,,,,,,
s2037,Movie,#Alive,Cho Il,"Yoo Ah-in, Park Shin-hye",South Korea,"September 8, 2020",2020,TV-MA,99 min,"Horror Movies, International Movies, Thrillers","As a grisly virus rampages a city, a lone man ..."
s2305,Movie,#AnneFrank - Parallel Stories,"Sabina Fedeli, Anna Migotto","Helen Mirren, Gengher Gatti",Italy,"July 1, 2020",2019,TV-14,95 min,"Documentaries, International Movies","Through her diary, Anne Frank's story is retol..."
s2482,Movie,#FriendButMarried,Rako Prijanto,"Adipati Dolken, Vanesha Prescilla, Rendi Jhon,...",Indonesia,"May 21, 2020",2018,TV-G,102 min,"Dramas, International Movies, Romantic Movies","Pining for his high school crush for years, a ..."
s2325,Movie,#FriendButMarried 2,Rako Prijanto,"Adipati Dolken, Mawar de Jongh, Sari Nila, Von...",Indonesia,"June 28, 2020",2020,TV-G,104 min,"Dramas, International Movies, Romantic Movies",As Ayu and Ditto finally transition from best ...
s5974,Movie,#Roxy,Michael Kennedy,"Jake Short, Sarah Fisher, Booboo Stewart, Dann...",Canada,"April 10, 2019",2018,TV-14,105 min,"Comedies, Romantic Movies",A teenage hacker with a huge nose helps a cool...
s5696,Movie,#Rucker50,Robert McCullough Jr.,NaN,United States,"December 1, 2016",2016,TV-PG,56 min,"Documentaries, Sports Movies",This documentary celebrates the 50th anniversa...
s655,Movie,#Selfie,Cristina Jacob,"Flavia Hojda, Crina Semciuc, Olimpia Melinte, ...",Romania,"June 21, 2021",2014,TV-MA,125 min,"Comedies, Dramas, International Movies","Two days before their final exams, three teen ..."
s656,Movie,#Selfie 69,Cristina Jacob,"Maia Morgenstern, Olimpia Melinte, Crina Semci...",Romania,"June 21, 2021",2016,TV-MA,119 min,"Comedies, Dramas, International Movies","After a painful breakup, a trio of party-lovin..."
s2667,TV Show,#blackAF,NaN,"Kenya Barris, Rashida Jones, Iman Benson, Genn...",United States,"April 17, 2020",2020,TV-MA,1 Season,TV Comedies,Kenya Barris and his family navigate relations...
s5973,Movie,#cats_the_mewvie,Michael Margolis,NaN,Canada,"February 5, 2020",2020,TV-14,90 min,"Documentaries, International Movies",This pawesome documentary explores how our fel...

### Q64. Sort by **release_year** descending AND **title** ascending at the same time (list of columns + list of ascending values).

In [109]:
# Coding 
df.sort_values(by= ["release_year", "title"], ascending = [False, True])

,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
show_id,,,,,,,,,,,
s1374,TV Show,50M2,NaN,"Engin Öztürk, Kürşat Alnıaçık, Cengiz Bozkurt,...",Turkey,"January 27, 2021",2021,TV-MA,1 Season,"International TV Shows, TV Dramas, TV Thrillers","Seeking to uncover the truth about his past, a..."
s1151,Movie,7 Yards: The Chris Norton Story,Jonathon Link,Chris Norton,United States,"March 30, 2021",2021,TV-PG,93 min,Documentaries,The true story of former college football play...
s851,Movie,99 Songs,Vishwesh Krishnamoorthy,"Ehan Bhat, Edilsy Vargas, Manisha Koirala, Lis...",India,"May 21, 2021",2021,TV-14,131 min,"Dramas, International Movies, Music & Musicals",Challenged to compose 100 songs before he can ...
s852,Movie,99 Songs (Tamil),NaN,NaN,NaN,"May 21, 2021",2021,TV-14,131 min,"Dramas, International Movies, Music & Musicals",Challenged to compose 100 songs before he can ...
s853,Movie,99 Songs (Telugu),NaN,NaN,NaN,"May 21, 2021",2021,TV-14,131 min,"Dramas, International Movies, Music & Musicals",Challenged to compose 100 songs before he can ...
...,...,...,...,...,...,...,...,...,...,...,...
s8764,Movie,WWII: Report from the Aleutians,John Huston,NaN,United States,"March 31, 2017",1943,TV-PG,45 min,Documentaries,Filmmaker John Huston narrates this Oscar-nomi...
s8740,Movie,Why We Fight: The Battle of Russia,"Frank Capra, Anatole Litvak",NaN,United States,"March 31, 2017",1943,TV-PG,82 min,Documentaries,This installment of Frank Capra's acclaimed do...
s7791,Movie,Prelude to War,Frank Capra,NaN,United States,"March 31, 2017",1942,TV-14,52 min,"Classic Movies, Documentaries",Frank Capra's documentary chronicles the rise ...
s8206,Movie,The Battle of Midway,John Ford,"Henry Fonda, Jane Darwell",United States,"March 31, 2017",1942,TV-14,18 min,"Classic Movies, Documentaries",Director John Ford captures combat footage of ...
s4251,TV Show,Pioneers: First Women Filmmakers*,NaN,NaN,NaN,"December 30, 2018",1925,TV-14,1 Season,TV Shows,This collection restores films from women who ...

### Q65. Sort by **rating**, and show only **title** and **rating** in the result.

In [110]:
# Coding 
df.sort_values(by= "rating")[["title", "rating"]]

                                                     title  rating
show_id
s5814                 Louis C.K.: Live at the Comedy Store  66 min
s5542                                      Louis C.K. 2017  74 min
s5795                                Louis C.K.: Hilarious  84 min
s8467                            The Princess and the Frog       G
s6152                                     An American Tail       G
...                                                    ...     ...
s7989                                             Sex Doll      UR
s5990    13TH: A Conversation with Oprah Winfrey & Ava ...     NaN
s6828                    Gargantia on the Verdurous Planet     NaN
s7313                                         Little Lunch     NaN
s7538                                 My Honor Was Loyalty     NaN

[8807 rows x 2 columns]

### Q66. Sort the **index** using **sort_index()** (useful after filtering).

In [111]:
# Codiing
df.sort_index()

,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
show_id,,,,,,,,,,,
s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
s10,Movie,The Starling,Theodore Melfi,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",United States,"September 24, 2021",2021,PG-13,104 min,"Comedies, Dramas",A woman adjusting to life after a loss contend...
s100,TV Show,On the Verge,NaN,"Julie Delpy, Elisabeth Shue, Sarah Jones, Alex...","France, United States","September 7, 2021",2021,TV-MA,1 Season,"TV Comedies, TV Dramas","Four women — a chef, a single mom, an heiress ..."
s1000,Movie,Stowaway,Joe Penna,"Anna Kendrick, Toni Collette, Daniel Dae Kim, ...","Germany, United States","April 22, 2021",2021,TV-MA,116 min,"Dramas, International Movies, Thrillers",A three-person crew on a mission to Mars faces...
s1001,Movie,Wild Dog,Ahishor Solomon,"Nagarjuna Akkineni, Dia Mirza, Saiyami Kher, A...",NaN,"April 22, 2021",2020,TV-MA,126 min,"Action & Adventure, International Movies",A brash but brilliant Indian intelligence agen...
...,...,...,...,...,...,...,...,...,...,...,...
s995,Movie,This Lady Called Life,Kayode Kasum,"Bisola Aiyeola, Efa Iwara, Molawa Onajobi, Tin...",Nigeria,"April 23, 2021",2020,TV-14,120 min,"Dramas, International Movies, Romantic Movies","Abandoned by her family, young single mother A..."
s996,Movie,Vizontele,"Yılmaz Erdoğan, Ömer Faruk Sorak","Yılmaz Erdoğan, Demet Akbağ, Altan Erkekli, Ce...",Turkey,"April 23, 2021",2001,TV-MA,106 min,"Comedies, Dramas, International Movies","In 1974, a rural town in Anatolia gets its fir..."
s997,Movie,HOMUNCULUS,Takashi Shimizu,"Go Ayano, Ryo Narita, Yukino Kishii, Anna Ishi...",Japan,"April 22, 2021",2021,TV-MA,116 min,"Horror Movies, International Movies, Thrillers",Truth and illusion blurs when a homeless amnes...
s998,TV Show,Life in Color with David Attenborough,NaN,David Attenborough,"Australia, United Kingdom","April 22, 2021",2021,TV-PG,1 Season,"British TV Shows, Docuseries, International TV...","Using innovative technology, this docuseries e..."
s999,Movie,Searching For Sheela,NaN,Ma Anand Sheela,India,"April 22, 2021",2021,TV-14,58 min,"Documentaries, International Movies",Journalists and fans await Ma Anand Sheela as ...

### Q67. Show the 5 oldest Movies (filter first, then sort, then head).

In [112]:
# Coding 
a = df.loc[df["type"]== "Movie"]   # Filtering
a

,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
show_id,,,,,,,,,,,
s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
s7,Movie,My Little Pony: A New Generation,"Robert Cullen, José Luis Ucha","Vanessa Hudgens, Kimiko Glenn, James Marsden, ...",NaN,"September 24, 2021",2021,PG,91 min,Children & Family Movies,Equestria's divided. But a bright-eyed hero be...
s8,Movie,Sankofa,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...","United States, Ghana, Burkina Faso, United Kin...","September 24, 2021",1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies","On a photo shoot in Ghana, an American model s..."
s10,Movie,The Starling,Theodore Melfi,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",United States,"September 24, 2021",2021,PG-13,104 min,"Comedies, Dramas",A woman adjusting to life after a loss contend...
s13,Movie,Je Suis Karl,Christian Schwochow,"Luna Wedler, Jannis Niewöhner, Milan Peschel, ...","Germany, Czech Republic","September 23, 2021",2021,TV-MA,127 min,"Dramas, International Movies",After most of her family is murdered in a terr...
...,...,...,...,...,...,...,...,...,...,...,...
s8802,Movie,Zinzana,Majid Al Ansari,"Ali Suliman, Saleh Bakri, Yasa, Ali Al-Jabri, ...","United Arab Emirates, Jordan","March 9, 2016",2015,TV-MA,96 min,"Dramas, International Movies, Thrillers",Recovering alcoholic Talal wakes up inside a s...
s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [113]:
# Coding 
a.sort_values(by= "release_year").head(5)    # Sorting

,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
show_id,,,,,,,,,,,
s7791,Movie,Prelude to War,Frank Capra,NaN,United States,"March 31, 2017",1942,TV-14,52 min,"Classic Movies, Documentaries",Frank Capra's documentary chronicles the rise ...
s8206,Movie,The Battle of Midway,John Ford,"Henry Fonda, Jane Darwell",United States,"March 31, 2017",1942,TV-14,18 min,"Classic Movies, Documentaries",Director John Ford captures combat footage of ...
s8661,Movie,Undercover: How to Operate Behind Enemy Lines,John Ford,NaN,United States,"March 31, 2017",1943,TV-PG,61 min,"Classic Movies, Documentaries",This World War II-era training film dramatizes...
s8764,Movie,WWII: Report from the Aleutians,John Huston,NaN,United States,"March 31, 2017",1943,TV-PG,45 min,Documentaries,Filmmaker John Huston narrates this Oscar-nomi...
s8740,Movie,Why We Fight: The Battle of Russia,"Frank Capra, Anatole Litvak",NaN,United States,"March 31, 2017",1943,TV-PG,82 min,Documentaries,This installment of Frank Capra's acclaimed do...

### Q68. Show the 5 newest TV Shows.

In [114]:
# Coding 
x= df.loc[df["type"]== "TV Show"]      # Filtering 
x

,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
show_id,,,,,,,,,,,
s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
s6,TV Show,Midnight Mass,Mike Flanagan,"Kate Siegel, Zach Gilford, Hamish Linklater, H...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries",The arrival of a charismatic young priest brin...
...,...,...,...,...,...,...,...,...,...,...,...
s8796,TV Show,Yu-Gi-Oh! Arc-V,NaN,"Mike Liscio, Emily Bauer, Billy Bob Thompson, ...","Japan, Canada","May 1, 2018",2015,TV-Y7,2 Seasons,"Anime Series, Kids' TV",Now that he's discovered the Pendulum Summonin...
s8797,TV Show,Yunus Emre,NaN,"Gökhan Atalay, Payidar Tüfekçioglu, Baran Akbu...",Turkey,"January 17, 2017",2016,TV-PG,2 Seasons,"International TV Shows, TV Dramas","During the Mongol invasions, Yunus Emre leaves..."
s8798,TV Show,Zak Storm,NaN,"Michael Johnston, Jessica Gee-George, Christin...","United States, France, South Korea, Indonesia","September 13, 2018",2016,TV-Y7,3 Seasons,Kids' TV,Teen surfer Zak Storm is mysteriously transpor...
s8801,TV Show,Zindagi Gulzar Hai,NaN,"Sanam Saeed, Fawad Khan, Ayesha Omer, Mehreen ...",Pakistan,"December 15, 2016",2012,TV-PG,1 Season,"International TV Shows, Romantic TV Shows, TV ...","Strong-willed, middle-class Kashaf and carefre..."
s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."

In [115]:
# Coding
x.sort_values(by= "release_year", ascending = False).head(5)      # Sorting

,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
show_id,,,,,,,,,,,
s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
s836,TV Show,Eden,NaN,"Marika Kono, Kentaro Ito, Kyoko Hikami, Tarusu...",NaN,"May 27, 2021",2021,TV-PG,1 Season,"Anime Series, International TV Shows",A human girl secretly raised by robots starts ...
s877,TV Show,Alma Matters,NaN,NaN,India,"May 14, 2021",2021,TV-MA,1 Season,"Docuseries, International TV Shows",Alumni of India’s elite academic institutes sh...
s875,TV Show,Booba: Food Puzzle,NaN,"Artem Kretov, Elena Solovieva, Vyacheslav Kataev",United Kingdom,"May 15, 2021",2021,TV-Y,1 Season,Kids' TV,Curious Booba is now a chef! With friends Lool...
s863,TV Show,Special,NaN,"Ryan O'Connell, Jessica Hecht, Punam Patel, Ma...",United States,"May 20, 2021",2021,TV-MA,2 Seasons,TV Comedies,A young gay man with cerebral palsy branches o...

### Q69. Sort by **country** and put the missing values **first** (hint: **na_position="first"**).

In [116]:
# Coding 
df.sort_values(by = "country", na_position="first").head (10)

,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
show_id,,,,,,,,,,,
s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
s6,TV Show,Midnight Mass,Mike Flanagan,"Kate Siegel, Zach Gilford, Hamish Linklater, H...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries",The arrival of a charismatic young priest brin...
s7,Movie,My Little Pony: A New Generation,"Robert Cullen, José Luis Ucha","Vanessa Hudgens, Kimiko Glenn, James Marsden, ...",NaN,"September 24, 2021",2021,PG,91 min,Children & Family Movies,Equestria's divided. But a bright-eyed hero be...
s11,TV Show,"Vendetta: Truth, Lies and The Mafia",NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, Docuseries, International TV S...","Sicily boasts a bold ""Anti-Mafia"" coalition. B..."
s12,TV Show,Bangkok Breaking,Kongkiat Komesiri,"Sukollawat Kanarot, Sushar Manaying, Pavarit M...",NaN,"September 23, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...","Struggling to earn a living in Bangkok, a man ..."
s14,Movie,Confessions of an Invisible Girl,Bruno Garotti,"Klara Castanho, Lucca Picon, Júlia Gomes, Marc...",NaN,"September 22, 2021",2021,TV-PG,91 min,"Children & Family Movies, Comedies",When the clever but socially-awkward Tetê join...
s15,TV Show,Crime Stories: India Detectives,NaN,NaN,NaN,"September 22, 2021",2021,TV-MA,1 Season,"British TV Shows, Crime TV Shows, Docuseries",Cameras following Bengaluru police on the job ...
s17,Movie,Europe's Most Dangerous Man: Otto Skorzeny in ...,"Pedro de Echave García, Pablo Azorín Williams",NaN,NaN,"September 22, 2021",2020,TV-MA,67 min,"Documentaries, International Movies",Declassified documents reveal the post-WWII li...
s19,Movie,Intrusion,Adam Salky,"Freida Pinto, Logan Marshall-Green, Robert Joh...",NaN,"September 22, 2021",2021,TV-14,94 min,Thrillers,After a deadly home invasion at a couple’s new...

#### Q70. What does **ascending=[False, True]** mean when sorting by two columns? Demonstrate with **release_year** and **title** and explain in a comment.

In [117]:
# Coding
df.sort_values(by= ["release_year", "title"], ascending = [False, True]).head(10)

# Note* Ascending= [False, True] it is usually used to sort multiple columns in both ways, ascending and descending at the same time. Here, the release_year column is sort 
# in descending order whereas, title column is sort in ascending order. In some case, if the both columns appears to have same data it will sort differently.

,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
show_id,,,,,,,,,,,
s1374,TV Show,50M2,NaN,"Engin Öztürk, Kürşat Alnıaçık, Cengiz Bozkurt,...",Turkey,"January 27, 2021",2021,TV-MA,1 Season,"International TV Shows, TV Dramas, TV Thrillers","Seeking to uncover the truth about his past, a..."
s1151,Movie,7 Yards: The Chris Norton Story,Jonathon Link,Chris Norton,United States,"March 30, 2021",2021,TV-PG,93 min,Documentaries,The true story of former college football play...
s851,Movie,99 Songs,Vishwesh Krishnamoorthy,"Ehan Bhat, Edilsy Vargas, Manisha Koirala, Lis...",India,"May 21, 2021",2021,TV-14,131 min,"Dramas, International Movies, Music & Musicals",Challenged to compose 100 songs before he can ...
s852,Movie,99 Songs (Tamil),NaN,NaN,NaN,"May 21, 2021",2021,TV-14,131 min,"Dramas, International Movies, Music & Musicals",Challenged to compose 100 songs before he can ...
s853,Movie,99 Songs (Telugu),NaN,NaN,NaN,"May 21, 2021",2021,TV-14,131 min,"Dramas, International Movies, Music & Musicals",Challenged to compose 100 songs before he can ...
s405,Movie,9to5: The Story of a Movement,NaN,NaN,NaN,"July 22, 2021",2021,TV-MA,85 min,Documentaries,"In this documentary, female office workers in ..."
s464,Movie,A Classic Horror Story,"Roberto De Feo, Paolo Strippoli","Matilda Lutz, Francesco Russo, Peppino Mazzott...",Italy,"July 14, 2021",2021,TV-MA,95 min,"Horror Movies, International Movies","In this gruesome suspense film, strangers trav..."
s684,Movie,A Family,Michihito Fujii,"Go Ayano, Hiroshi Tachi, Machiko Ono, Yukiya K...",NaN,"June 18, 2021",2021,TV-MA,135 min,"Dramas, International Movies","Taken in by the yakuza at a young age, Kenji s..."
s453,Movie,A Perfect Fit,Hadrah Daeng Ratu,"Nadya Arina, Refal Hady, Giorgino Abraham, Ang...",Indonesia,"July 15, 2021",2021,TV-PG,113 min,"Comedies, Dramas, International Movies",Sparks fly when a fashion blogger in Bali meet...
s394,Movie,A Second Chance: Rivals!,Clay Glen,"Emily Morris, Stella Shute, Eva Grados, India ...",Australia,"July 23, 2021",2021,PG,91 min,"Children & Family Movies, Sports Movies",Crushed when she doesn't qualify for the Olymp...

## **Section E — Updating Data**

### Q71. Rename the column **listed_in** to **genres** (keep this change).

In [118]:
# Coding
df.rename(columns={"listed_in":"genres"}, inplace = True)
df

,type,title,director,cast,country,date_added,release_year,rating,duration,genres,description
show_id,,,,,,,,,,,
s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
...,...,...,...,...,...,...,...,...,...,...,...
s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

### Q72. Create a new column **age_years** = 2026 minus **release_year**.

In [119]:
# Coding 
df.loc[:, "age_years"]= 2026 - df["release_year"]
df

,type,title,director,cast,country,date_added,release_year,rating,duration,genres,description,age_years
show_id,,,,,,,,,,,,
s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",6
s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",5
s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,5
s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",5
s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,5
...,...,...,...,...,...,...,...,...,...,...,...,...
s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a...",19
s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g...",8
s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...,17
s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero...",20
s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...,11

### Q73. Create a column **is_movie** that is **True** when **type** is **"Movie"**.

In [120]:
# Coding 
df.loc[:, "is_movie"]= df["type"]=="Movie"
df

,type,title,director,cast,country,date_added,release_year,rating,duration,genres,description,age_years,is_movie
show_id,,,,,,,,,,,,,
s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",6,True
s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",5,False
s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,5,False
s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",5,False
s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,5,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a...",19,True
s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g...",8,False
s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...,17,True
s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero...",20,True
s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...,11,True

### Q74. Create a column **is_recent** that is **True** when **release_year >= 2020**.

In [121]:
# Coding 
df.loc[:, "is_recent"]= df["release_year"]>= 2020
df

,type,title,director,cast,country,date_added,release_year,rating,duration,genres,description,age_years,is_movie,is_recent
show_id,,,,,,,,,,,,,,
s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",6,True,True
s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",5,False,True
s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,5,False,True
s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",5,False,True
s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,5,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a...",19,True,False
s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g...",8,False,False
s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...,17,True,False
s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero...",20,True,False
s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...,11,True,False

### Q75. Using **.loc** with a condition, set **rating** to **"UNRATED"** for all rows where **rating** is missing.

In [122]:
# Coding
df.loc[df["rating"].isna(), "rating"] = "UNRATED"
df

,type,title,director,cast,country,date_added,release_year,rating,duration,genres,description,age_years,is_movie,is_recent
show_id,,,,,,,,,,,,,,
s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",6,True,True
s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",5,False,True
s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,5,False,True
s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",5,False,True
s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,5,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a...",19,True,False
s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g...",8,False,False
s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...,17,True,False
s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero...",20,True,False
s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...,11,True,False

### Q76. Replace the value **"United States"** with **"USA"** in the **country** column (hint: **replace**).

In [123]:
# Coding 
df.loc[df["country"]== "United States", "country"] = "USA"
df

,type,title,director,cast,country,date_added,release_year,rating,duration,genres,description,age_years,is_movie,is_recent
show_id,,,,,,,,,,,,,,
s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,USA,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",6,True,True
s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",5,False,True
s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,5,False,True
s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",5,False,True
s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,5,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",USA,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a...",19,True,False
s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g...",8,False,False
s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",USA,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...,17,True,False
s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",USA,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero...",20,True,False
s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...,11,True,False

### Q77. Convert all titles to UPPERCASE into a new column **title_upper** (hint: **str.upper**).

In [124]:
# Coding 
df.loc[:, "title_upper"] = df["title"].str.upper()
df

,type,title,director,cast,country,date_added,release_year,rating,duration,genres,description,age_years,is_movie,is_recent,title_upper
show_id,,,,,,,,,,,,,,,
s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,USA,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",6,True,True,DICK JOHNSON IS DEAD
s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",5,False,True,BLOOD & WATER
s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,5,False,True,GANGLANDS
s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",5,False,True,JAILBIRDS NEW ORLEANS
s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,5,False,True,KOTA FACTORY
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",USA,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a...",19,True,False,ZODIAC
s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g...",8,False,False,ZOMBIE DUMB
s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",USA,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...,17,True,False,ZOMBIELAND
s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",USA,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero...",20,True,False,ZOOM
s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...,11,True,False,ZUBAAN

### Q78. Create a column **title_length** = number of characters in each title (hint: **str.len**).

In [125]:
# Coding 
df.loc[:, "title_length"] = df["title"].str.len()
df


# Note* it also count the space between the letters.

,type,title,director,cast,country,date_added,release_year,rating,duration,genres,description,age_years,is_movie,is_recent,title_upper,title_length
show_id,,,,,,,,,,,,,,,,
s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,USA,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",6,True,True,DICK JOHNSON IS DEAD,20
s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",5,False,True,BLOOD & WATER,13
s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,5,False,True,GANGLANDS,9
s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",5,False,True,JAILBIRDS NEW ORLEANS,21
s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,5,False,True,KOTA FACTORY,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",USA,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a...",19,True,False,ZODIAC,6
s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g...",8,False,False,ZOMBIE DUMB,11
s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",USA,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...,17,True,False,ZOMBIELAND,10
s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",USA,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero...",20,True,False,ZOOM,4
s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...,11,True,False,ZUBAAN,6

### Q79. Using **.loc**, change the **title** of the row with index label 0 to **"My Favourite Show"**. Display that row to confirm.

In [126]:
# Coding 
df.loc[0, "title"]= "My Favourite Show"
df.head(2)

,type,title,director,cast,country,date_added,release_year,rating,duration,genres,description,age_years,is_movie,is_recent,title_upper,title_length
show_id,,,,,,,,,,,,,,,,
s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,USA,"September 25, 2021",2020.0,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",6.0,True,True,DICK JOHNSON IS DEAD,20.0
s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021.0,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",5.0,False,True,BLOOD & WATER,13.0

### Q80. Add a column **platform** where every row has the value **"Netflix"**.

In [127]:
# Coding 
df.loc[:, "platform"]= "Netflix"
df

,type,title,director,cast,country,date_added,release_year,rating,duration,genres,description,age_years,is_movie,is_recent,title_upper,title_length,platform
show_id,,,,,,,,,,,,,,,,,
s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,USA,"September 25, 2021",2020.0,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",6.0,True,True,DICK JOHNSON IS DEAD,20.0,Netflix
s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021.0,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",5.0,False,True,BLOOD & WATER,13.0,Netflix
s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021.0,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,5.0,False,True,GANGLANDS,9.0,Netflix
s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021.0,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",5.0,False,True,JAILBIRDS NEW ORLEANS,21.0,Netflix
s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021.0,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,5.0,False,True,KOTA FACTORY,12.0,Netflix
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018.0,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g...",8.0,False,False,ZOMBIE DUMB,11.0,Netflix
s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",USA,"November 1, 2019",2009.0,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...,17.0,True,False,ZOMBIELAND,10.0,Netflix
s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",USA,"January 11, 2020",2006.0,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero...",20.0,True,False,ZOOM,4.0,Netflix
s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015.0,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...,11.0,True,False,ZUBAAN,6.0,Netflix
0,NaN,My Favourite Show,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Netflix

### Q82. Change **release_year** to type **int32** using **astype**. Check with **dtypes**.

In [128]:
# Coding 
df.loc["release_year"]= df["release_year"].astype("Int64")
df

,type,title,director,cast,country,date_added,release_year,rating,duration,genres,description,age_years,is_movie,is_recent,title_upper,title_length,platform
show_id,,,,,,,,,,,,,,,,,
s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,USA,"September 25, 2021",2020.0,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",6.0,True,True,DICK JOHNSON IS DEAD,20.0,Netflix
s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021.0,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",5.0,False,True,BLOOD & WATER,13.0,Netflix
s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021.0,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,5.0,False,True,GANGLANDS,9.0,Netflix
s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021.0,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",5.0,False,True,JAILBIRDS NEW ORLEANS,21.0,Netflix
s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021.0,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,5.0,False,True,KOTA FACTORY,12.0,Netflix
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",USA,"November 1, 2019",2009.0,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...,17.0,True,False,ZOMBIELAND,10.0,Netflix
s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",USA,"January 11, 2020",2006.0,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero...",20.0,True,False,ZOOM,4.0,Netflix
s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015.0,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...,11.0,True,False,ZUBAAN,6.0,Netflix
0,NaN,My Favourite Show,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Netflix
release_year,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [129]:
df.dtypes

type             object
title            object
director         object
cast             object
country          object
date_added       object
release_year    float64
rating           object
duration         object
genres           object
description      object
age_years       float64
is_movie         object
is_recent        object
title_upper      object
title_length    float64
platform         object
dtype: object

### Q83. Using **.loc** with a condition, create/overwrite a column **era** = **"old"** for titles before 2010 and **"new"** for 2010 onward (two **.loc** assignments, or **np.where**).

In [130]:
# Coding 
df.loc[df["release_year"]> 2010, "era"]= "new"
df.loc[df["release_year"]< 2010, "era"]= "old"
df

,type,title,director,cast,country,date_added,release_year,rating,duration,genres,description,age_years,is_movie,is_recent,title_upper,title_length,platform,era
show_id,,,,,,,,,,,,,,,,,,
s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,USA,"September 25, 2021",2020.0,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",6.0,True,True,DICK JOHNSON IS DEAD,20.0,Netflix,new
s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021.0,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",5.0,False,True,BLOOD & WATER,13.0,Netflix,new
s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021.0,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,5.0,False,True,GANGLANDS,9.0,Netflix,new
s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021.0,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",5.0,False,True,JAILBIRDS NEW ORLEANS,21.0,Netflix,new
s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021.0,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,5.0,False,True,KOTA FACTORY,12.0,Netflix,new
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",USA,"November 1, 2019",2009.0,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...,17.0,True,False,ZOMBIELAND,10.0,Netflix,old
s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",USA,"January 11, 2020",2006.0,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero...",20.0,True,False,ZOOM,4.0,Netflix,old
s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015.0,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...,11.0,True,False,ZUBAAN,6.0,Netflix,new
0,NaN,My Favourite Show,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Netflix,NaN
release_year,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Q84. Increase **age_years** by 1 for **all** rows in one operation.

In [131]:
# Coding 
df.loc[:, "age_year"] = df["age_years"]+1
df

,type,title,director,cast,country,date_added,release_year,rating,duration,genres,description,age_years,is_movie,is_recent,title_upper,title_length,platform,era,age_year
show_id,,,,,,,,,,,,,,,,,,,
s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,USA,"September 25, 2021",2020.0,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",6.0,True,True,DICK JOHNSON IS DEAD,20.0,Netflix,new,7.0
s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021.0,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",5.0,False,True,BLOOD & WATER,13.0,Netflix,new,6.0
s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021.0,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,5.0,False,True,GANGLANDS,9.0,Netflix,new,6.0
s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021.0,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",5.0,False,True,JAILBIRDS NEW ORLEANS,21.0,Netflix,new,6.0
s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021.0,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,5.0,False,True,KOTA FACTORY,12.0,Netflix,new,6.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",USA,"November 1, 2019",2009.0,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...,17.0,True,False,ZOMBIELAND,10.0,Netflix,old,18.0
s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",USA,"January 11, 2020",2006.0,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero...",20.0,True,False,ZOOM,4.0,Netflix,old,21.0
s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015.0,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...,11.0,True,False,ZUBAAN,6.0,Netflix,new,12.0
0,NaN,My Favourite Show,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Netflix,NaN,NaN
release_year,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Q85. Explain in a markdown comment: why is **df.loc[condition, "col"] = value** the SAFE way to update, instead of **df[condition]["col"] = value**? (SettingWithCopyWarning!)

**Answer**: 

**df.loc[condition,"col"]=value** is the safe way to update because, when we use **.loc** the data will changed or update permanently and we don't need to use **inplace =True** again and again. However, if we just use, **df[condition, "col"]=value**, we have to use **inplace= True** eveytime, because without **.loc or inplace = True**, the data only changed temporarly.

## **Section F — GroupBy**

### Q86. Group by **type** and count the number of titles in each group (**size()**).

In [132]:
# Coding 
df.groupby("type").size()

type
Movie      6131
TV Show    2676
dtype: int64

### Q87. Group by **rating** and count titles. Which rating is most common?

In [133]:
# Coding 
df.groupby("rating").size()

rating
66 min         1
74 min         1
84 min         1
G             41
NC-17          3
NR            80
PG           287
PG-13        490
R            799
TV-14       2160
TV-G         220
TV-MA       3207
TV-PG        863
TV-Y         307
TV-Y7        334
TV-Y7-FV       6
UNRATED        4
UR             3
dtype: int64

In [ ]:
# Coding 
df.groupby("rating").size().idxmax()

### Q88. Group by **release_year** and count titles. Which year had the most releases?

In [134]:
#Coding
df.groupby("release_year").size()

release_year
1925.0       1
1942.0       2
1943.0       3
1944.0       3
1945.0       4
          ...
2017.0    1032
2018.0    1147
2019.0    1030
2020.0     953
2021.0     592
Length: 74, dtype: int64

In [ ]:
# Coding 
df.groupby("release_year").size().idxmax()

### Q89. Group by **type** and find the **minimum** and **maximum** **release_year** for each (hint: **agg(["min","max"])**).

In [135]:
# Coding 
df.groupby("type")["release_year"].agg(["min", "max"])

            min     max
type
Movie    1942.0  2021.0
TV Show  1925.0  2021.0

### Q90. Group by **type** and compute the **average** **age_years**.

In [136]:
# Coding 
df.groupby("type")["release_year"].mean()

type
Movie      2013.121514
TV Show    2016.605755
Name: release_year, dtype: float64

### Q91. Group by **country** and count titles — show only the top 10 (sort + head).

In [137]:
# Coding 
df.groupby("country").size().sort_values(ascending=False).head(10)

country
USA               2818
India              972
United Kingdom     419
Japan              245
South Korea        199
Canada             181
Spain              145
France             124
Mexico             110
Egypt              106
dtype: int64

### Q92. Group by **rating** and compute the average **title_length**.

In [138]:
# Coding 
df.groupby("rating")["title_length"].mean()

rating
66 min      36.000000
74 min      15.000000
84 min      21.000000
G           20.560976
NC-17       17.666667
NR          16.075000
PG          18.285714
PG-13       16.014286
R           14.898623
TV-14       16.661111
TV-G        21.900000
TV-MA       17.304334
TV-PG       19.250290
TV-Y        23.540717
TV-Y7       25.089820
TV-Y7-FV    28.000000
UNRATED     29.750000
UR          16.666667
Name: title_length, dtype: float64

### Q93. Group by **era** (from Q83) and count Movies vs TV Shows (hint: group by TWO columns).

In [139]:
# Coding 
df.groupby(["era", "type"]).size()

era  type
new  Movie      4824
     TV Show    2454
old  Movie      1153
     TV Show     182
dtype: int64

### Q94. Group by **type** and **rating** together and count. Display the result with **unstack()**.

In [140]:
# Coding 
df.groupby(["type", "rating"]).size().unstack()

rating,66 min,74 min,84 min,G,NC-17,NR,PG,PG-13,R,TV-14,TV-G,TV-MA,TV-PG,TV-Y,TV-Y7,TV-Y7-FV,UNRATED,UR
type,,,,,,,,,,,,,,,,,,
Movie,1.0,1.0,1.0,41.0,3.0,75.0,287.0,490.0,797.0,1427.0,126.0,2062.0,540.0,131.0,139.0,5.0,2.0,3.0
TV Show,NaN,NaN,NaN,NaN,NaN,5.0,NaN,NaN,2.0,733.0,94.0,1145.0,323.0,176.0,195.0,1.0,2.0,NaN

### Q95. For Movies only: group by **release_year** and count — how many movies came out each year since 2015? (filter first, then group, then **.tail()**)

In [141]:
# Coding 
df.loc[(df["type"]== "Movie") & (df["release_year"]>= 2015), :].groupby("release_year").size().tail()

release_year
2017.0    767
2018.0    767
2019.0    633
2020.0    517
2021.0    277
dtype: int64

### Q96. Group by **country** and compute the average **release_year** — which 5 countries have the **newest** catalogs on average? (sort descending, head)

In [142]:
# Coding 
df.groupby("country")["release_year"].mean().sort_values(ascending= False).head(5)

country
Egypt, Denmark, Germany     2021.0
Uruguay, Germany            2021.0
, South Korea               2021.0
Belgium, United Kingdom     2021.0
Mexico, France, Colombia    2021.0
Name: release_year, dtype: float64

#### Q97. Use **value_counts()** on **genres** — why does this NOT give clean genre counts? Explain in a comment (hint: multiple genres in one cell).

In [143]:
# Coding 
df.loc["genres"].value_counts()

# Note* 
# value_counts() does not give clean individual genre counts because
# multiple genres can be stored in a single cell, such as
# "Action, Comedy, Drama". Pandas treats the entire cell as one value
# instead of counting Action, Comedy, and Drama separately.

KeyError: 'genres'

In [144]:
df

,type,title,director,cast,country,date_added,release_year,rating,duration,genres,description,age_years,is_movie,is_recent,title_upper,title_length,platform,era,age_year
show_id,,,,,,,,,,,,,,,,,,,
s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,USA,"September 25, 2021",2020.0,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",6.0,True,True,DICK JOHNSON IS DEAD,20.0,Netflix,new,7.0
s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021.0,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",5.0,False,True,BLOOD & WATER,13.0,Netflix,new,6.0
s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021.0,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,5.0,False,True,GANGLANDS,9.0,Netflix,new,6.0
s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021.0,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",5.0,False,True,JAILBIRDS NEW ORLEANS,21.0,Netflix,new,6.0
s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021.0,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,5.0,False,True,KOTA FACTORY,12.0,Netflix,new,6.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",USA,"November 1, 2019",2009.0,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...,17.0,True,False,ZOMBIELAND,10.0,Netflix,old,18.0
s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",USA,"January 11, 2020",2006.0,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero...",20.0,True,False,ZOOM,4.0,Netflix,old,21.0
s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015.0,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...,11.0,True,False,ZUBAAN,6.0,Netflix,new,12.0
0,NaN,My Favourite Show,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Netflix,NaN,NaN
release_year,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Q98. Group by **is_recent** and count — how many recent vs old titles?

In [145]:
# Coding 
df.groupby("is_recent").size()

is_recent
False    7262
True     1545
dtype: int64

### Q99. Group by **type** and use **.agg()** with a dictionary: count of **title** and mean of **age_years** in ONE command.

In [146]:
# Coding 
df.groupby("type").agg({
    "title": "count", 
    "age_years": "mean"
})

         title  age_years
type
Movie     6131  12.878486
TV Show   2676   9.394245

### Q100. Group by **rating** and show the **number of unique countries** per rating (hint: **nunique**).

In [147]:
# Coding 
df.groupby("rating")["country"].nunique()

rating
66 min        1
74 min        1
84 min        1
G            12
NC-17         3
NR           31
PG           67
PG-13       121
R           182
TV-14       169
TV-G         42
TV-MA       314
TV-PG       108
TV-Y         55
TV-Y7        60
TV-Y7-FV      5
UNRATED       3
UR            3
Name: country, dtype: int64

### Q101. Using **groupby** + **head(1)**, show the FIRST title (by current order) in each **type** group.

In [148]:
# Coding 
df.groupby("type").head(1)

,type,title,director,cast,country,date_added,release_year,rating,duration,genres,description,age_years,is_movie,is_recent,title_upper,title_length,platform,era,age_year
show_id,,,,,,,,,,,,,,,,,,,
s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,USA,"September 25, 2021",2020.0,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",6.0,True,True,DICK JOHNSON IS DEAD,20.0,Netflix,new,7.0
s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021.0,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",5.0,False,True,BLOOD & WATER,13.0,Netflix,new,6.0

### Q102. Group by **release_year** and count, then plot it with **.plot()** (line chart). What trend do you see?

In [149]:
# Coding 
#import matplotlib.pyplot as plt

#y = df.groupby("release_year")["title"].size()
#y.plot(kind="line", figsize= (10,5))

#plt.title("Number of Titles Released by year")
#plt.xlabel("Release Year")
#plt.ylabel("Number of Titles")
#plt.grid(True)
#plt.show()

### Q103. Group by **year_added**-style logic isn't possible yet — **date_added** is still text! Group by the **first 4 characters trick is wrong**. Explain in a comment why we need Section G (Cleaning) before we can group by the year a title was ADDED.

In [ ]:
# We need Section G (Cleaning) because date_added is stored as text.
# The first 4 characters trick is wrong because the date format may
# not always begin with the year, and missing or inconsistent values
# can cause incorrect results.
# We should convert date_added into datetime format first, then
# extract the year using .dt.year before grouping.

### Q104. Group by **type** and compute the **median** **release_year**.

In [150]:
# Coding 
df.groupby("type")["release_year"].median()

type
Movie      2016.0
TV Show    2018.0
Name: release_year, dtype: float64

### Q105. Challenge: for each **rating**, what percentage of titles are Movies? (hint: group by rating, compute the mean of **is_movie**, multiply by 100)

In [151]:
# Coding 
df.groupby("rating")["is_movie"].mean()*100

rating
66 min      100.000000
74 min      100.000000
84 min      100.000000
G           100.000000
NC-17       100.000000
NR           93.750000
PG          100.000000
PG-13       100.000000
R            99.749687
TV-14        66.064815
TV-G         57.272727
TV-MA        64.296851
TV-PG        62.572422
TV-Y         42.671010
TV-Y7        41.616766
TV-Y7-FV     83.333333
UNRATED      50.000000
UR          100.000000
Name: is_movie, dtype: float64

In [152]:
df.head(5)

,type,title,director,cast,country,date_added,release_year,rating,duration,genres,description,age_years,is_movie,is_recent,title_upper,title_length,platform,era,age_year
show_id,,,,,,,,,,,,,,,,,,,
s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,USA,"September 25, 2021",2020.0,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",6.0,True,True,DICK JOHNSON IS DEAD,20.0,Netflix,new,7.0
s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021.0,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",5.0,False,True,BLOOD & WATER,13.0,Netflix,new,6.0
s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021.0,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,5.0,False,True,GANGLANDS,9.0,Netflix,new,6.0
s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021.0,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",5.0,False,True,JAILBIRDS NEW ORLEANS,21.0,Netflix,new,6.0
s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021.0,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,5.0,False,True,KOTA FACTORY,12.0,Netflix,new,6.0

## **Section G — Cleaning**

### Q106. Re-check missing values per column (things changed since Section A!).

In [153]:
# Coding 
df.shape

(8809, 19)

In [154]:
# Coding 
df.isnull().sum()

type               2
title              1
director        2636
cast             827
country          833
date_added        12
release_year       2
rating             2
duration           5
genres             2
description        2
age_years          2
is_movie           2
is_recent          2
title_upper        2
title_length       2
platform           1
era              196
age_year           2
dtype: int64

In [155]:
# Converting all the missing values into percentage, so that it will be easy to decide and act either to fill or delete the column. 
# Coding 
(df.isnull().mean()*100).round(1)

type             0.0
title            0.0
director        29.9
cast             9.4
country          9.5
date_added       0.1
release_year     0.0
rating           0.0
duration         0.1
genres           0.0
description      0.0
age_years        0.0
is_movie         0.0
is_recent        0.0
title_upper      0.0
title_length     0.0
platform         0.0
era              2.2
age_year         0.0
dtype: float64

### Q107. Fill missing **director** values with **"Unknown"**.

In [156]:
# Coding 
df["director"]= df["director"].fillna("Unknown")

In [157]:
# Checking 
df.isnull().sum()

type              2
title             1
director          0
cast            827
country         833
date_added       12
release_year      2
rating            2
duration          5
genres            2
description       2
age_years         2
is_movie          2
is_recent         2
title_upper       2
title_length      2
platform          1
era             196
age_year          2
dtype: int64

### Q108. Fill missing **cast** values with **"Unknown"**.

In [158]:
# Coding 
df["cast"]= df["cast"].fillna("Unknown")

In [159]:
# Checking 
df.isnull().sum()

type              2
title             1
director          0
cast              0
country         833
date_added       12
release_year      2
rating            2
duration          5
genres            2
description       2
age_years         2
is_movie          2
is_recent         2
title_upper       2
title_length      2
platform          1
era             196
age_year          2
dtype: int64

### Q109. Fill missing **country** values with the **most common** country (hint: **mode()[0]**).

In [160]:
# Coding 
df.loc[df["country"].isna(), "country"]= df["country"].mode()[0]

In [161]:
# Checking 
df.isnull().sum()

type              2
title             1
director          0
cast              0
country           0
date_added       12
release_year      2
rating            2
duration          5
genres            2
description       2
age_years         2
is_movie          2
is_recent         2
title_upper       2
title_length      2
platform          1
era             196
age_year          2
dtype: int64

### Q110. Count the rows where **date_added** is missing, then drop those rows.

In [162]:
# Coding 
df["date_added"].isna().sum()

12

In [163]:
# Coding
df= df.dropna(subset= ["date_added"])

In [164]:
# Checking 
df.isnull().sum()

type              0
title             0
director          0
cast              0
country           0
date_added        0
release_year      0
rating            0
duration          3
genres            0
description       0
age_years         0
is_movie          0
is_recent         0
title_upper       0
title_length      0
platform          0
era             193
age_year          0
dtype: int64

### Q111. **date_added** has extra spaces in some rows — strip them (hint: **str.strip**).

In [165]:
# Coding 
df["date_added"]= df["date_added"].str.strip()

C:\Users\HP\AppData\Local\Temp\ipykernel_25588\3632073081.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["date_added"]= df["date_added"].str.strip()

### Q112. Convert **date_added** to datetime with **pd.to_datetime**. Check the dtype after.

In [166]:
# Coding 
df["date_added"]=pd.to_datetime(df["date_added"])

C:\Users\HP\AppData\Local\Temp\ipykernel_25588\3190639511.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["date_added"]=pd.to_datetime(df["date_added"])

In [167]:
# Checking 
df["date_added"].dtype

dtype('<M8[ns]')

### Q113. NOW create **year_added** = **.dt.year** and **month_added** = **.dt.month_name()**.

In [168]:
# Coding 
df["year_added"]= df["date_added"].dt.year
df["month_added"]= df["date_added"].dt.month_name()
df[["date_added", "year_added", "month_added"]].head()

C:\Users\HP\AppData\Local\Temp\ipykernel_25588\1965786462.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["year_added"]= df["date_added"].dt.year
C:\Users\HP\AppData\Local\Temp\ipykernel_25588\1965786462.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["month_added"]= df["date_added"].dt.month_name()

        date_added  year_added month_added
show_id
s1      2021-09-25        2021   September
s2      2021-09-24        2021   September
s3      2021-09-24        2021   September
s4      2021-09-24        2021   September
s5      2021-09-24        2021   September

In [169]:
# Coding 
df["month_added"]= df["date_added"].dt.month_name()

C:\Users\HP\AppData\Local\Temp\ipykernel_25588\856999446.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["month_added"]= df["date_added"].dt.month_name()

In [170]:
df[["date_added", "year_added", "month_added"]].head()

        date_added  year_added month_added
show_id
s1      2021-09-25        2021   September
s2      2021-09-24        2021   September
s3      2021-09-24        2021   September
s4      2021-09-24        2021   September
s5      2021-09-24        2021   September

### Q114. Group by **year_added** and count — which year did Netflix add the most content? (This is the question F103 could not answer!)

In [171]:
# Coding 
df.groupby("year_added").count()

,type,title,director,cast,country,date_added,release_year,rating,duration,genres,description,age_years,is_movie,is_recent,title_upper,title_length,platform,era,age_year,month_added
year_added,,,,,,,,,,,,,,,,,,,,
2008,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
2009,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
2010,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
2011,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,12,13,13
2012,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,2,3,3
2013,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11
2014,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24
2015,82,82,82,82,82,82,82,82,82,82,82,82,82,82,82,82,82,81,82,82
2016,429,429,429,429,429,429,429,429,427,429,429,429,429,429,429,429,429,418,429,429
2017,1188,1188,1188,1188,1188,1188,1188,1188,1187,1188,1188,1188,1188,1188,1188,1188,1188,1159,1188,1188
2018,1649,1649,1649,1649,1649,1649,1649,1649,1649,1649,1649,1649,1649,1649,1649,1649,1649,1606,1649,1649
2019,2016,2016,2016,2016,2016,2016,2016,2016,2016,2016,2016,2016,2016,2016,2016,2016,2016,1978,2016,2016
2020,1879,1879,1879,1879,1879,1879,1879,1879,1879,1879,1879,1879,1879,1879,1879,1879,1879,1846,1879,1879
2021,1498,1498,1498,1498,1498,1498,1498,1498,1498,1498,1498,1498,1498,1498,1498,1498,1498,1462,1498,1498

In [ ]:
df

#### Q115. Group by **month_added** and count — which month is most popular for adding content?

In [172]:
# Coding 
df.groupby("month_added").count()

,type,title,director,cast,country,date_added,release_year,rating,duration,genres,description,age_years,is_movie,is_recent,title_upper,title_length,platform,era,age_year,year_added
month_added,,,,,,,,,,,,,,,,,,,,
April,764,764,764,764,764,764,764,764,763,764,764,764,764,764,764,764,764,750,764,764
August,755,755,755,755,755,755,755,755,754,755,755,755,755,755,755,755,755,735,755,755
December,813,813,813,813,813,813,813,813,813,813,813,813,813,813,813,813,813,797,813,813
February,563,563,563,563,563,563,563,563,563,563,563,563,563,563,563,563,563,556,563,563
January,738,738,738,738,738,738,738,738,738,738,738,738,738,738,738,738,738,716,738,738
July,827,827,827,827,827,827,827,827,827,827,827,827,827,827,827,827,827,810,827,827
June,728,728,728,728,728,728,728,728,728,728,728,728,728,728,728,728,728,718,728,728
March,742,742,742,742,742,742,742,742,742,742,742,742,742,742,742,742,742,721,742,742
May,632,632,632,632,632,632,632,632,632,632,632,632,632,632,632,632,632,619,632,632
November,705,705,705,705,705,705,705,705,705,705,705,705,705,705,705,705,705,687,705,705
October,760,760,760,760,760,760,760,760,760,760,760,760,760,760,760,760,760,747,760,760
September,770,770,770,770,770,770,770,770,769,770,770,770,770,770,770,770,770,748,770,770

### Q116. Look at the **duration** column with **unique()** (first 20 values) — what TWO different formats do you see?

In [173]:
# Coding 
df["duration"].nunique()

220

In [ ]:
# Coding 
df.groupby("type")["duration"].nunique()

### Q117. Extract the number from **duration** into a new column **duration_int** (hint: **str.extract(r"(\\d+)")** then **astype(float)**).

In [174]:
# Coding 
df["duration_int"]= df["duration"].str.extract(r"(\d+)").astype(float)
df[["duration", "duration_int"]].head(10)

C:\Users\HP\AppData\Local\Temp\ipykernel_25588\2205194583.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["duration_int"]= df["duration"].str.extract(r"(\d+)").astype(float)

          duration  duration_int
show_id
s1          90 min          90.0
s2       2 Seasons           2.0
s3        1 Season           1.0
s4        1 Season           1.0
s5       2 Seasons           2.0
s6        1 Season           1.0
s7          91 min          91.0
s8         125 min         125.0
s9       9 Seasons           9.0
s10        104 min         104.0

### Q118. For Movies only: what is the average, minimum, and maximum duration in minutes?

In [175]:
# Coding 
df.loc[df["type"]== "Movie", "duration_int"].agg(["mean", "min", "max"])

mean     99.577187
min       3.000000
max     312.000000
Name: duration_int, dtype: float64

### Q119. For TV Shows only: how many have more than 5 seasons? Show their titles.

In [176]:
# Coding 
u = df[(df["type"]== "TV Show") & (df["duration_int"]>=5)]
len(u)

160

### Q120. Check duplicated **titles** (not full rows): are there any titles that appear more than once? Display them.

In [177]:
# Coding 
df.duplicated().sum()

0

In [ ]:
# Coding 
df.loc[df.duplicated(), "title"]

### Q122. The **rating** column contains some WRONG values that are actually durations (like **"74 min"**) — find them (hint: **str.contains("min", na=False)**).

In [178]:
# Coding 
r = df.loc[df["rating"].str.contains("min", na=False), ["title", 'type', 'rating']]
r

                                        title   type  rating
show_id
s5542                         Louis C.K. 2017  Movie  74 min
s5795                   Louis C.K.: Hilarious  Movie  84 min
s5814    Louis C.K.: Live at the Comedy Store  Movie  66 min

### Q123. Fix those wrong rating rows: set their **rating** to **"UNRATED"** using **.loc**.

In [179]:
# Coding 
r.loc[:, "rating"]= "UNRATEED"
r

                                        title   type    rating
show_id
s5542                         Louis C.K. 2017  Movie  UNRATEED
s5795                   Louis C.K.: Hilarious  Movie  UNRATEED
s5814    Louis C.K.: Live at the Comedy Store  Movie  UNRATEED

### Q124. Final check: run **info()** and **isna().sum()** — is the dataset clean now? Summarize what you fixed in a comment.

In [180]:
# Coding 
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8797 entries, s1 to s8807
Data columns (total 22 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   type          8797 non-null   object
 1   title         8797 non-null   object
 2   director      8797 non-null   object
 3   cast          8797 non-null   object
 4   country       8797 non-null   object
 5   date_added    8797 non-null   datetime64[ns]
 6   release_year  8797 non-null   float64
 7   rating        8797 non-null   object
 8   duration      8794 non-null   object
 9   genres        8797 non-null   object
 10  description   8797 non-null   object
 11  age_years     8797 non-null   float64
 12  is_movie      8797 non-null   object
 13  is_recent     8797 non-null   object
 14  title_upper   8797 non-null   object
 15  title_length  8797 non-null   float64
 16  platform      8797 non-null   object
 17  era           8604 non-null   object
 18  age_year      8797 non-null   float64
 19  year_added    8797 non-null   int64
 20  month_added   8797 non-null   object
 21  duration_int  8794 non-null   float64
dtypes: datetime64[ns](1), float64(5), int64(1), object(15)
memory usage: 1.5+ MB

In [181]:
# Coding 
df.isna().sum()

type              0
title             0
director          0
cast              0
country           0
date_added        0
release_year      0
rating            0
duration          3
genres            0
description       0
age_years         0
is_movie          0
is_recent         0
title_upper       0
title_length      0
platform          0
era             193
age_year          0
year_added        0
month_added       0
duration_int      3
dtype: int64

In [182]:
df

,type,title,director,cast,country,date_added,release_year,rating,duration,genres,...,is_movie,is_recent,title_upper,title_length,platform,era,age_year,year_added,month_added,duration_int
show_id,,,,,,,,,,,,,,,,,,,,,
s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,Unknown,USA,2021-09-25,2020.0,PG-13,90 min,Documentaries,...,True,True,DICK JOHNSON IS DEAD,20.0,Netflix,new,7.0,2021,September,90.0
s2,TV Show,Blood & Water,Unknown,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,2021-09-24,2021.0,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries",...,False,True,BLOOD & WATER,13.0,Netflix,new,6.0,2021,September,2.0
s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",USA,2021-09-24,2021.0,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",...,False,True,GANGLANDS,9.0,Netflix,new,6.0,2021,September,1.0
s4,TV Show,Jailbirds New Orleans,Unknown,Unknown,USA,2021-09-24,2021.0,TV-MA,1 Season,"Docuseries, Reality TV",...,False,True,JAILBIRDS NEW ORLEANS,21.0,Netflix,new,6.0,2021,September,1.0
s5,TV Show,Kota Factory,Unknown,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,2021-09-24,2021.0,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",...,False,True,KOTA FACTORY,12.0,Netflix,new,6.0,2021,September,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",USA,2019-11-20,2007.0,R,158 min,"Cult Movies, Dramas, Thrillers",...,True,False,ZODIAC,6.0,Netflix,old,20.0,2019,November,158.0
s8804,TV Show,Zombie Dumb,Unknown,Unknown,USA,2019-07-01,2018.0,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies",...,False,False,ZOMBIE DUMB,11.0,Netflix,new,9.0,2019,July,2.0
s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",USA,2019-11-01,2009.0,R,88 min,"Comedies, Horror Movies",...,True,False,ZOMBIELAND,10.0,Netflix,old,18.0,2019,November,88.0
s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",USA,2020-01-11,2006.0,PG,88 min,"Children & Family Movies, Comedies",...,True,False,ZOOM,4.0,Netflix,old,21.0,2020,January,88.0
s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,2019-03-02,2015.0,TV-14,111 min,"Dramas, International Movies, Music & Musicals",...,True,False,ZUBAAN,6.0,Netflix,new,12.0,2019,March,111.0

### Q125. Save your cleaned DataFrame to a new file **netflix_clean.csv** (without the index). This file is your submission proof!

In [ ]:
# Coding 
df.to_csv("netflix_clean.csv", index= False)
print("Saved netflix_clean.csv")